namespace SshManager.Core.Localization;

/// <summary>
/// Translations, side by side so a missing language is impossible. Format placeholders ({0}) must match in both.
/// </summary>
internal static class Strings
{
    public static readonly Dictionary<string, (string Ru, string En)> Table = new()
    {
        // ---------- common ----------
        ["Common.Save"] = ("Сохранить", "Save"),
        ["Common.Cancel"] = ("Отмена", "Cancel"),
        ["Common.Close"] = ("Закрыть", "Close"),
        ["Common.Error"] = ("ОШИБКА:", "ERROR:"),
        ["App.ErrorTitle"] = ("SSH Manager — ошибка", "SSH Manager — error"),
        ["Lang.System"] = ("Как в Windows", "Windows default"),

        // ---------- menu ----------
        ["Menu.File"] = ("_Файл", "_File"),
        ["Menu.NewServer"] = ("Новый сервер…", "New server…"),
        ["Menu.BackupNow"] = ("Сделать бэкап сейчас", "Back up now"),
        ["Menu.OpenDataFolder"] = ("Открыть папку данных", "Open data folder"),
        ["Menu.Lock"] = ("Заблокировать", "Lock"),
        ["Menu.Exit"] = ("Выход", "Exit"),
        ["Menu.View"] = ("_Вид", "_View"),
        ["Menu.ExpandAll"] = ("Развернуть все группы", "Expand all groups"),
        ["Menu.CollapseAll"] = ("Свернуть все", "Collapse all"),
        ["Menu.RefreshAll"] = ("Обновить информацию о серверах", "Refresh server information"),
        ["Menu.Language"] = ("_Язык (Language)", "_Language (Язык)"),
        ["Menu.Help"] = ("_Справка", "_Help"),
        ["Menu.About"] = ("О программе", "About"),
        ["About.Title"] = ("О программе", "About"),
        ["About.Text"] = ("SSH Manager {0}\n\nСерверы, ключи, SSH-агент, мониторинг и пробросы портов.\n\nПапка данных:\n{1}",
            "SSH Manager {0}\n\nServers, keys, SSH agent, monitoring and port forwarding.\n\nData folder:\n{1}"),

        // ---------- tabs / main ----------
        ["Tab.Servers"] = ("Серверы", "Servers"),
        ["Tab.Keys"] = ("Ключи", "Keys"),
        ["Tab.Settings"] = ("Настройки", "Settings"),
        ["Main.Connect"] = ("Подключиться", "Connect"),
        ["Main.AddServer"] = ("+ Сервер", "+ Server"),
        ["Main.Edit"] = ("Изменить", "Edit"),
        ["Main.SetupKey"] = ("Настроить вход по ключу", "Set up key login"),
        ["Main.SetupKeyTip"] = ("Войти по паролю, установить ключ в authorized_keys и переключить сервер на ключ",
            "Log in with the password, install a key into authorized_keys and switch the server to key login"),
        ["Main.Test"] = ("Проверить", "Test"),
        ["Main.PortForwards"] = ("Пробросы портов", "Port forwards"),
        ["Main.RefreshAllTip"] = ("Обновить ОС, регион, контейнеры и статус всех серверов (F5)",
            "Refresh OS, location, containers and status of all servers (F5)"),
        ["Main.RefreshingAll"] = ("Обновляю информацию о серверах…", "Refreshing server information…"),
        ["Main.Search"] = ("Поиск:", "Search:"),
        ["Main.SearchTip"] = ("Поиск по названию, адресу, группе, заметкам, ОС, региону, контейнерам (Ctrl+F)",
            "Search by name, address, group, notes, OS, location, containers (Ctrl+F)"),
        ["Main.Lock"] = ("Заблокировать", "Lock"),
        ["Main.Summary"] = ("Серверов: {0} (онлайн {1}, недоступно {2})   Ключей: {3}",
            "Servers: {0} ({1} online, {2} down)   Keys: {3}"),
        ["Main.SessionOpened"] = ("Открыта сессия: {0}", "Session opened: {0}"),
        ["Main.SessionFailed"] = ("Не удалось открыть сессию", "Could not open the session"),
        ["Main.CopySuffix"] = (" (копия)", " (copy)"),
        ["Main.DeleteServerConfirm"] = ("Удалить сервер «{0}» ({1})?\nКлючи останутся в хранилище.",
            "Delete server \"{0}\" ({1})?\nKeys stay in the vault."),
        ["Main.CommandCopied"] = ("Команда ssh скопирована в буфер обмена", "ssh command copied to the clipboard"),
        ["Main.Testing"] = ("Проверка подключения к {0}…", "Testing connection to {0}…"),
        ["Main.TestOkStatus"] = ("{0}: подключение успешно", "{0}: connection OK"),
        ["Main.TestFailedStatus"] = ("{0}: ошибка подключения", "{0}: connection failed"),
        ["Main.TestTitle"] = ("Проверка подключения", "Connection test"),
        ["Main.TestOk"] = ("Подключение к {0} успешно.\n\n{1}", "Connected to {0} successfully.\n\n{1}"),
        ["Main.TestFailed"] = ("Не удалось подключиться к {0}:\n\n{1}", "Could not connect to {0}:\n\n{1}"),
        ["Agent.NotRunning"] = ("Агент не запущен (pipe занят другим приложением)", "Agent is not running (the pipe is used by another app)"),
        ["Agent.Default"] = ("Агент: \\\\.\\pipe\\{0} — доступен для ssh, git, VS Code", "Agent: \\\\.\\pipe\\{0} — available to ssh, git, VS Code"),
        ["Agent.Fallback"] = ("Агент: \\\\.\\pipe\\{0} (стандартный pipe занят; для внешних клиентов задайте SSH_AUTH_SOCK)",
            "Agent: \\\\.\\pipe\\{0} (the standard pipe is busy; set SSH_AUTH_SOCK for external clients)"),

        // ---------- columns ----------
        ["Col.Name"] = ("Название", "Name"),
        ["Col.Address"] = ("Адрес", "Address"),
        ["Col.Os"] = ("ОС", "OS"),
        ["Col.Cpu"] = ("CPU", "CPU"),
        ["Col.Mem"] = ("Память", "Memory"),
        ["Col.Region"] = ("Регион", "Location"),
        ["Col.Forwards"] = ("Пробросы", "Forwards"),
        ["Col.Auth"] = ("Вход", "Login"),
        ["Col.LastConnected"] = ("Последнее подключение", "Last connected"),
        ["Col.Notes"] = ("Заметки", "Notes"),
        ["Auth.Password"] = ("Пароль", "Password"),
        ["Auth.KeyMissing"] = ("ключ не найден", "key not found"),

        // ---------- tree ----------
        ["Tree.GroupOffline"] = ("⚠ недоступно: {0}", "⚠ {0} down"),
        ["Tree.Updated"] = ("Обновлено: {0}", "Updated: {0}"),
        ["Tree.Error"] = ("Ошибка:", "Error:"),
        ["Tree.Isp"] = ("Провайдер:", "ISP:"),
        ["Tree.Loading"] = ("Загрузка информации с сервера…", "Loading information from the server…"),
        ["Tree.NoData"] = ("Нет данных — «Обновить информацию» в контекстном меню", "No data yet — use \"Refresh info\" in the context menu"),
        ["Tree.Docker"] = ("Docker ({0}/{1})", "Docker ({0}/{1})"),
        ["Tree.NoContainers"] = ("Контейнеров нет", "No containers"),
        ["Tree.Services"] = ("Сервисы ({0}/{1})", "Services ({0}/{1})"),
        ["Tree.ForwardsSection"] = ("Пробросы ({0})", "Forwards ({0})"),
        ["Tree.Incoming"] = ("← с {0}: {1} {2} → :{3}", "← from {0}: {1} {2} → :{3}"),

        // ---------- context menu ----------
        ["Ctx.Connect"] = ("Подключиться", "Connect"),
        ["Ctx.Install"] = ("Установить", "Install"),
        ["Ctx.PortForwards"] = ("Пробросы портов…", "Port forwards…"),
        ["Ctx.RefreshInfo"] = ("Обновить информацию", "Refresh info"),
        ["Ctx.CheckNow"] = ("Проверить доступность сейчас", "Check availability now"),
        ["Ctx.Edit"] = ("Изменить…", "Edit…"),
        ["Ctx.Duplicate"] = ("Дублировать…", "Duplicate…"),
        ["Ctx.CopyCommand"] = ("Копировать команду ssh", "Copy ssh command"),
        ["Ctx.SetupKey"] = ("Настроить вход по ключу…", "Set up key login…"),
        ["Ctx.Test"] = ("Проверить подключение", "Test connection"),
        ["Ctx.Delete"] = ("Удалить", "Delete"),
        ["Ctx.ContainerLogs"] = ("Логи контейнера", "Container logs"),
        ["Ctx.ContainerRestart"] = ("Перезапустить контейнер", "Restart container"),
        ["Ctx.ServiceStatus"] = ("Статус сервиса", "Service status"),
        ["Ctx.ServiceLogs"] = ("Журнал сервиса", "Service log"),
        ["Ctx.ServiceRestart"] = ("Перезапустить сервис", "Restart service"),
        ["Ctx.AddServer"] = ("Добавить сервер в группу…", "Add server to this group…"),

        // ---------- health / metrics ----------
        ["Health.OnlineTip"] = ("Доступен, {0} мс (проверка в {1})", "Online, {0} ms (checked at {1})"),
        ["Health.OfflineTip"] = ("Недоступен (проверка в {0})\n{1}", "Down (checked at {0})\n{1}"),
        ["Health.Checking"] = ("Проверка…", "Checking…"),
        ["Health.Disabled"] = ("Мониторинг выключен для этого сервера", "Monitoring is off for this server"),
        ["Health.JumpHost"] = ("Через jump-хост — не проверяется", "Behind a jump host — not checked"),
        ["Health.Unknown"] = ("Ещё не проверялся", "Not checked yet"),
        ["Health.NoBanner"] = ("Порт открыт, но SSH не ответил", "Port is open but SSH did not answer"),
        ["Health.Timeout"] = ("Нет ответа (таймаут)", "No answer (timeout)"),
        ["Health.DownTitle"] = ("Сервер недоступен", "Server is down"),
        ["Health.DownText"] = ("{0}: {1}", "{0}: {1}"),
        ["Metrics.Cpu"] = ("CPU: {0:0}% (load {1:0.00}, ядер: {2})", "CPU: {0:0}% (load {1:0.00}, {2} cores)"),
        ["Metrics.Mem"] = ("Память: {0} из {1} ({2:0}%)", "Memory: {0} of {1} ({2:0}%)"),
        ["Metrics.Disk"] = ("Диск /: {0} из {1} ({2:0}%)", "Disk /: {0} of {1} ({2:0}%)"),
        ["Metrics.Uptime"] = ("Аптайм: {0} д {1} ч {2} мин", "Uptime: {0} d {1} h {2} min"),
        ["Metrics.Collected"] = ("Снято в {0}", "Collected at {0}"),

        // ---------- host keys / ssh ----------
        ["HostKey.Title"] = ("Проверка ключа сервера", "Server key check"),
        ["HostKey.Changed"] = ("ВНИМАНИЕ: ключ сервера {0} ИЗМЕНИЛСЯ!\n\nЭто может означать переустановку сервера или атаку «человек посередине».\n\nНовый ключ: {1}\n{2}\n\nЗаменить сохранённый ключ и продолжить?",
            "WARNING: the key of server {0} HAS CHANGED!\n\nThe server may have been reinstalled — or this is a man-in-the-middle attack.\n\nNew key: {1}\n{2}\n\nReplace the stored key and continue?"),
        ["HostKey.New"] = ("Первое подключение к {0}.\n\nКлюч сервера: {1}\n{2}\n\nДоверять этому серверу и сохранить его ключ?",
            "First connection to {0}.\n\nServer key: {1}\n{2}\n\nTrust this server and save its key?"),
        ["Ssh.HostKeyNotTrusted"] = ("Ключ сервера {0} ещё не подтверждён — подключитесь к нему один раз вручную",
            "The key of server {0} is not confirmed yet — connect to it once manually"),
        ["Ssh.CommandTimeout"] = ("Команда на сервере не завершилась вовремя", "The command on the server timed out"),
        ["Launch.NoKey"] = ("У сервера «{0}» не выбран ключ", "No key selected for server \"{0}\""),
        ["Launch.NoPassword"] = ("У сервера «{0}» не сохранён пароль", "No password saved for server \"{0}\""),
        ["Inventory.JumpHost"] = ("Серверы за jump-хостом не опрашиваются", "Servers behind a jump host are not queried"),
        ["Inventory.Failed"] = ("Не удалось получить информацию:", "Could not collect information:"),

        // ---------- vault / ipc / cli ----------
        ["Vault.Exists"] = ("Хранилище уже существует", "The vault already exists"),
        ["Vault.Locked"] = ("Хранилище заблокировано", "The vault is locked"),
        ["Vault.Corrupt"] = ("Файл хранилища повреждён или имеет неизвестный формат", "The vault file is damaged or has an unknown format"),
        ["Vault.WrongPassword"] = ("Неверный мастер-пароль", "Wrong master password"),
        ["Key.UnsupportedType"] = ("Тип ключа {0} не поддерживается. Поддерживаются Ed25519 и RSA.", "Key type {0} is not supported. Ed25519 and RSA are."),
        ["Ipc.Closed"] = ("SSH Manager закрыл соединение", "SSH Manager closed the connection"),
        ["Ipc.Empty"] = ("Пустой ответ", "Empty response"),
        ["Ipc.NoPassword"] = ("Нет пароля", "No password"),
        ["Ipc.UnknownOp"] = ("Неизвестная команда {0}", "Unknown command {0}"),
        ["Ipc.ServerNotFound"] = ("Сервер «{0}» не найден (sshm list — список)", "Server \"{0}\" not found (sshm list shows all)"),
        ["Ipc.ServerAmbiguous"] = ("Подходит несколько серверов:", "Several servers match:"),
        ["Cli.Help"] = ("SSH Manager — консольный помощник\n  sshm <имя сервера|хост>   подключиться к сохранённому серверу в этом окне\n  sshm list                 список серверов",
            "SSH Manager — console helper\n  sshm <server name|host>   connect to a saved server in this window\n  sshm list                 list servers"),
        ["Cli.SessionNotFound"] = ("сессия не найдена или устарела", "session not found or expired"),
        ["Cli.ConnectFailed"] = ("не удалось подключиться", "could not connect"),
        ["Cli.Starting"] = ("запускаю SSH Manager…", "starting SSH Manager…"),
        ["Cli.NotResponding"] = ("SSH Manager не отвечает", "SSH Manager is not responding"),
        ["Cli.NotRunning"] = ("SSH Manager не запущен", "SSH Manager is not running"),
        ["Cli.NewHostTitle"] = ("SSH Manager — новый сервер", "SSH Manager — new server"),
        ["Cli.PasswordRejected"] = ("SSH Manager: сохранённый пароль не подошёл или сессия устарела.", "SSH Manager: the saved password was rejected or the session expired."),
        ["Cli.NoPassword"] = ("SSH Manager не запущен — пароль недоступен.", "SSH Manager is not running — no password available."),
        ["Cli.PressKey"] = ("Нажмите любую клавишу, чтобы закрыть окно…", "Press any key to close this window…"),

        // ---------- tray ----------
        ["Tray.StartedLocked"] = ("Работает в трее и заблокирован. Щёлкните, чтобы разблокировать.", "Running in the tray, locked. Click to unlock."),
        ["Tray.AgentNotRunning"] = ("не запущен", "not running"),
        ["Tray.Unlocked"] = ("разблокирован", "unlocked"),
        ["Tray.Locked"] = ("заблокирован", "locked"),
        ["Tray.Agent"] = ("Агент:", "Agent:"),
        ["Tray.Open"] = ("Открыть SSH Manager", "Open SSH Manager"),
        ["Tray.Connect"] = ("Подключиться", "Connect"),
        ["Tray.NoServers"] = ("(нет серверов)", "(no servers)"),
        ["Tray.Unlock"] = ("Разблокировать…", "Unlock…"),
        ["Tray.Lock"] = ("Заблокировать", "Lock"),
        ["Tray.Language"] = ("Язык (Language)", "Language (Язык)"),
        ["Tray.Exit"] = ("Выход", "Exit"),
        ["Tray.ByKey"] = ("Вход по ключу", "Key login"),
        ["Tray.ByPassword"] = ("Вход по паролю", "Password login"),

        // ---------- unlock / password ----------
        ["Unlock.Header"] = ("Разблокировать хранилище", "Unlock the vault"),
        ["Unlock.Subtitle"] = ("Введите мастер-пароль, чтобы открыть серверы и ключи.", "Enter the master password to open servers and keys."),
        ["Unlock.Password"] = ("Мастер-пароль", "Master password"),
        ["Unlock.Repeat"] = ("Повторите пароль", "Repeat the password"),
        ["Unlock.Autostart"] = ("Запускать вместе с Windows (в трее)", "Start with Windows (in the tray)"),
        ["Unlock.CryptoHint"] = ("Хранилище шифруется AES-256-GCM, ключ получается из пароля через Argon2id. Забытый мастер-пароль восстановить невозможно.",
            "The vault is encrypted with AES-256-GCM, the key is derived from the password with Argon2id. A forgotten master password cannot be recovered."),
        ["Unlock.Unlock"] = ("Разблокировать", "Unlock"),
        ["Unlock.CreateHeader"] = ("Создание хранилища", "Create the vault"),
        ["Unlock.CreateSubtitle"] = ("Придумайте мастер-пароль. Им шифруются все пароли серверов и приватные ключи в папке data.",
            "Choose a master password. It encrypts all server passwords and private keys in the data folder."),
        ["Unlock.Create"] = ("Создать", "Create"),
        ["Unlock.TooShort"] = ("Пароль должен быть не короче 8 символов.", "The password must be at least 8 characters."),
        ["Unlock.Mismatch"] = ("Пароли не совпадают.", "The passwords do not match."),
        ["ChangePwd.Title"] = ("Смена мастер-пароля", "Change master password"),
        ["ChangePwd.Current"] = ("Текущий пароль", "Current password"),
        ["ChangePwd.New"] = ("Новый пароль", "New password"),
        ["ChangePwd.Repeat"] = ("Повторите новый пароль", "Repeat the new password"),
        ["ChangePwd.Change"] = ("Сменить", "Change"),
        ["ChangePwd.TooShort"] = ("Новый пароль должен быть не короче 8 символов.", "The new password must be at least 8 characters."),
        ["ChangePwd.Done"] = ("Мастер-пароль изменён.", "The master password has been changed."),

        // ---------- server editor ----------
        ["Editor.Title"] = ("Сервер", "Server"),
        ["Editor.NewTitle"] = ("Новый сервер", "New server"),
        ["Editor.EditTitle"] = ("Сервер — {0}", "Server — {0}"),
        ["Editor.Name"] = ("Название", "Name"),
        ["Editor.Group"] = ("Группа", "Group"),
        ["Editor.GroupTip"] = ("Вложенные группы через «/», например VPN/Европа", "Nested groups with \"/\", e.g. VPN/Europe"),
        ["Editor.Host"] = ("IP-адрес или хост", "IP address or host"),
        ["Editor.Port"] = ("Порт", "Port"),
        ["Editor.User"] = ("Пользователь", "User"),
        ["Editor.Auth"] = ("Авторизация", "Authentication"),
        ["Editor.SshKey"] = ("SSH-ключ", "SSH key"),
        ["Editor.Show"] = ("Показать", "Show"),
        ["Editor.Key"] = ("Ключ", "Key"),
        ["Editor.NewKey"] = ("Новый ключ…", "New key…"),
        ["Editor.KeyHint"] = ("Пароль можно оставить сохранённым — он нужен кнопке «Настроить вход по ключу» и для sudo.",
            "You can keep the password saved — \"Set up key login\" and sudo use it."),
        ["Editor.Advanced"] = ("Дополнительно", "Advanced"),
        ["Editor.Jump"] = ("Jump-хост (ssh -J), например user@bastion:22", "Jump host (ssh -J), e.g. user@bastion:22"),
        ["Editor.ExtraArgs"] = ("Дополнительные аргументы ssh", "Extra ssh arguments"),
        ["Editor.Monitor"] = ("Проверка доступности, минут", "Availability check, minutes"),
        ["Editor.MonitorHint"] = ("Пусто — по умолчанию ({0} мин), 0 — не проверять", "Empty — default ({0} min), 0 — do not check"),
        ["Editor.Notes"] = ("Заметки", "Notes"),
        ["Editor.NeedHost"] = ("Укажите IP-адрес или имя хоста.", "Enter an IP address or host name."),
        ["Editor.BadPort"] = ("Порт должен быть числом от 1 до 65535.", "The port must be a number from 1 to 65535."),
        ["Editor.NeedUser"] = ("Укажите пользователя.", "Enter a user name."),
        ["Editor.NeedKey"] = ("Выберите ключ или создайте новый.", "Choose a key or create a new one."),
        ["Editor.BadMonitor"] = ("Интервал проверки — целое число минут (0 — выкл.).", "The check interval is a whole number of minutes (0 = off)."),

        // ---------- keys ----------
        ["Keys.Generate"] = ("+ Сгенерировать", "+ Generate"),
        ["Keys.Import"] = ("Импорт…", "Import…"),
        ["Keys.CopyPublic"] = ("Копировать публичный ключ", "Copy public key"),
        ["Keys.ExportPrivate"] = ("Экспорт приватного…", "Export private…"),
        ["Keys.Rename"] = ("Переименовать", "Rename"),
        ["Keys.Delete"] = ("Удалить", "Delete"),
        ["Keys.Type"] = ("Тип", "Type"),
        ["Keys.Fingerprint"] = ("Отпечаток", "Fingerprint"),
        ["Keys.Comment"] = ("Комментарий", "Comment"),
        ["Keys.Created"] = ("Создан", "Created"),
        ["Keys.Servers"] = ("Серверы", "Servers"),
        ["Keys.CreatedStatus"] = ("Ключ «{0}» создан", "Key \"{0}\" created"),
        ["Keys.ImportTitle"] = ("Импорт ключа", "Import key"),
        ["Keys.ImportFilter"] = ("Все файлы|*.*|PuTTY (*.ppk)|*.ppk|PEM (*.pem;*.key)|*.pem;*.key", "All files|*.*|PuTTY (*.ppk)|*.ppk|PEM (*.pem;*.key)|*.pem;*.key"),
        ["Keys.AlreadyExists"] = ("Этот ключ уже есть в хранилище.", "This key is already in the vault."),
        ["Keys.Imported"] = ("Ключ «{0}» импортирован ({1})", "Key \"{0}\" imported ({1})"),
        ["Keys.AskPassphrase"] = ("Ключ защищён паролем. Введите passphrase:", "The key is protected. Enter the passphrase:"),
        ["Keys.WrongPassphrase"] = ("Неверная passphrase. Попробуйте ещё раз:", "Wrong passphrase. Try again:"),
        ["Keys.ReadFailed"] = ("Не удалось прочитать ключ:", "Could not read the key:"),
        ["Keys.PublicCopied"] = ("Публичный ключ скопирован в буфер обмена", "Public key copied to the clipboard"),
        ["Keys.ExportWarning"] = ("Приватный ключ будет сохранён в файл БЕЗ шифрования.\nХраните этот файл в надёжном месте. Продолжить?",
            "The private key will be saved to a file WITHOUT encryption.\nKeep that file safe. Continue?"),
        ["Keys.ExportTitle"] = ("Экспорт приватного ключа", "Export private key"),
        ["Keys.Saved"] = ("Ключ сохранён: {0}", "Key saved: {0}"),
        ["Keys.RenameTitle"] = ("Переименовать ключ", "Rename key"),
        ["Keys.NewName"] = ("Новое название:", "New name:"),
        ["Keys.DeleteTitle"] = ("Удаление ключа", "Delete key"),
        ["Keys.InUse"] = ("Ключ используется серверами:\n{0}\n\nСначала переключите их на другой ключ или пароль.",
            "The key is used by:\n{0}\n\nSwitch those servers to another key or password first."),
        ["Keys.DeleteConfirm"] = ("Удалить ключ «{0}»?\n{1}\n\nЕсли у вас нет копии, восстановить его будет невозможно.",
            "Delete key \"{0}\"?\n{1}\n\nWithout a copy it cannot be recovered."),
        ["KeyGen.Title"] = ("Новый SSH-ключ", "New SSH key"),
        ["KeyGen.Comment"] = ("Комментарий (попадёт в authorized_keys)", "Comment (goes into authorized_keys)"),
        ["KeyGen.Ed25519"] = ("Ed25519 (рекомендуется)", "Ed25519 (recommended)"),
        ["KeyGen.Rsa"] = ("RSA 4096 (для старых серверов)", "RSA 4096 (for old servers)"),
        ["KeyGen.Generate"] = ("Сгенерировать", "Generate"),

        // ---------- key setup ----------
        ["KeySetup.Title"] = ("Настройка входа по ключу", "Key login setup"),
        ["KeySetup.Hint"] = ("Программа войдёт на сервер по сохранённому паролю, добавит публичный ключ в ~/.ssh/authorized_keys, проверит вход по ключу и переключит сервер на ключ. Вход по паролю на сервере не отключается.",
            "The app logs in with the saved password, adds the public key to ~/.ssh/authorized_keys, verifies key login and switches the server to the key. Password login on the server stays enabled."),
        ["KeySetup.Start"] = ("Настроить", "Set up"),
        ["KeySetup.GenerateNew"] = ("Сгенерировать новый ключ Ed25519", "Generate a new Ed25519 key"),
        ["KeySetup.Existing"] = ("Существующий:", "Existing:"),
        ["KeySetup.Done"] = ("Готово. Ключ: {0} ({1})", "Done. Key: {0} ({1})"),
        ["KeySetup.DoneButton"] = ("Готово", "Done"),
        ["KeySetup.NeedPassword"] = ("Для настройки нужен сохранённый пароль сервера", "A saved server password is required"),
        ["KeySetup.Connecting"] = ("Подключаюсь к {0} по паролю…", "Connecting to {0} with the password…"),
        ["KeySetup.PasswordOk"] = ("Вход по паролю выполнен.", "Password login succeeded."),
        ["KeySetup.KeyNotFound"] = ("Выбранный ключ не найден", "The selected key was not found"),
        ["KeySetup.UsingExisting"] = ("Использую существующий ключ «{0}» ({1}).", "Using the existing key \"{0}\" ({1})."),
        ["KeySetup.Generated"] = ("Сгенерирован новый ключ Ed25519 ({0}).", "Generated a new Ed25519 key ({0})."),
        ["KeySetup.BadChar"] = ("Недопустимый символ в публичном ключе", "Invalid character in the public key"),
        ["KeySetup.Adding"] = ("Добавляю ключ в ~/.ssh/authorized_keys…", "Adding the key to ~/.ssh/authorized_keys…"),
        ["KeySetup.WriteFailed"] = ("Не удалось записать authorized_keys:", "Could not write authorized_keys:"),
        ["KeySetup.Installed"] = ("Ключ установлен. Проверяю вход по ключу…", "Key installed. Checking key login…"),
        ["KeySetup.CheckFailed"] = ("Проверка входа по ключу не прошла", "Key login check failed"),
        ["KeySetup.KeyWorks"] = ("Вход по ключу работает.", "Key login works."),
        ["KeySetup.Switched"] = ("Сервер переключён на авторизацию по ключу. Пароль остаётся сохранённым — его можно удалить в настройках сервера.",
            "The server now uses key login. The password stays saved — you can remove it in the server settings."),

        // ---------- port forwards ----------
        ["Fwd.Title"] = ("Пробросы портов (iptables)", "Port forwards (iptables)"),
        ["Fwd.Hint"] = ("Трафик на порт этого сервера перенаправляется (DNAT + MASQUERADE) на другой сервер. Нужен root или sudo. Правила сохраняются после перезагрузки (netfilter-persistent / iptables-save).",
            "Traffic to a port of this server is redirected (DNAT + MASQUERADE) to another server. Requires root or sudo. Rules are kept across reboots (netfilter-persistent / iptables-save)."),
        ["Fwd.Protocol"] = ("Протокол", "Protocol"),
        ["Fwd.ListenPort"] = ("Порт", "Port"),
        ["Fwd.Target"] = ("Куда", "Target"),
        ["Fwd.Interface"] = ("Интерфейс", "Interface"),
        ["Fwd.CreatedBy"] = ("Создан", "Created by"),
        ["Fwd.External"] = ("внешний", "external"),
        ["Fwd.AddTitle"] = ("Новый проброс", "New forward"),
        ["Fwd.PortTip"] = ("Порт или диапазон 1000:2000", "Port or range 1000:2000"),
        ["Fwd.TargetServer"] = ("Целевой сервер или IP", "Target server or IP"),
        ["Fwd.TargetTip"] = ("Выберите сервер из списка или введите IP / хост", "Pick a server or type an IP / host"),
        ["Fwd.TargetPort"] = ("Порт цели", "Target port"),
        ["Fwd.TargetPortTip"] = ("Пусто — тот же порт", "Empty — same port"),
        ["Fwd.Add"] = ("Добавить", "Add"),
        ["Fwd.Refresh"] = ("Обновить", "Refresh"),
        ["Fwd.Delete"] = ("Удалить выбранный", "Delete selected"),
        ["Fwd.InstallPersist"] = ("Установить iptables-persistent", "Install iptables-persistent"),
        ["Fwd.InstallPersistConfirm"] = ("На сервере не найден способ сохранять правила iptables после перезагрузки.\nУстановить iptables-persistent (Debian/Ubuntu) или iptables-services (RHEL)?",
            "No way to keep iptables rules across reboots was found on the server.\nInstall iptables-persistent (Debian/Ubuntu) or iptables-services (RHEL)?"),
        ["Fwd.InstallingPersist"] = ("Устанавливаю пакет для сохранения правил…", "Installing the rule persistence package…"),
        ["Fwd.Reading"] = ("Читаю правила iptables на {0}…", "Reading iptables rules on {0}…"),
        ["Fwd.Found"] = ("Найдено пробросов: {0}", "Forwards found: {0}"),
        ["Fwd.FillFields"] = ("Укажите порт и цель.", "Enter a port and a target."),
        ["Fwd.Adding"] = ("Добавляю {0} {1} → {2}:{3}…", "Adding {0} {1} → {2}:{3}…"),
        ["Fwd.Added"] = ("Проброс добавлен.", "Forward added."),
        ["Fwd.DeleteConfirm"] = ("Удалить проброс {0} {1} → {2}?", "Delete forward {0} {1} → {2}?"),
        ["Fwd.Deleting"] = ("Удаляю проброс {0} {1}…", "Deleting forward {0} {1}…"),
        ["Fwd.Deleted"] = ("Проброс удалён.", "Forward deleted."),
        ["Fwd.Connecting"] = ("Подключаюсь к {0}…", "Connecting to {0}…"),
        ["Fwd.NeedRoot"] = ("Нужны права root: войдите как root или сохраните пароль пользователя с правом sudo.",
            "Root is required: log in as root or save the password of a sudo-capable user."),
        ["Fwd.Failed"] = ("Команда iptables не выполнилась:", "The iptables command failed:"),
        ["Fwd.Persisted"] = ("Правила сохранены ({0}).", "Rules saved ({0})."),
        ["Fwd.NotPersisted"] = ("Внимание: правила НЕ сохранятся после перезагрузки — нет netfilter-persistent / iptables-services.",
            "Warning: rules will NOT survive a reboot — no netfilter-persistent / iptables-services."),
        ["Fwd.BadProtocol"] = ("Протокол должен быть tcp или udp", "The protocol must be tcp or udp"),
        ["Fwd.BadPort"] = ("Неверный порт: {0}", "Invalid port: {0}"),
        ["Fwd.BadIp"] = ("Неверный IPv4-адрес: {0}", "Invalid IPv4 address: {0}"),
        ["Fwd.BadId"] = ("Неверный идентификатор правила: {0}", "Invalid rule id: {0}"),
        ["Fwd.NoRule"] = ("Не удалось определить правило для удаления", "Could not determine the rule to delete"),
        ["Fwd.CannotResolve"] = ("Не удалось определить IP для {0}", "Could not resolve {0}"),

        // ---------- scripts ----------
        ["Scripts.Title"] = ("Установочный скрипт", "Install script"),
        ["Scripts.NoneMenu"] = ("Нет скриптов — добавить в Настройках…", "No scripts — add some in Settings…"),
        ["Scripts.OtherOs"] = ("Для других ОС", "For other OSes"),
        ["Scripts.RunConfirm"] = ("Запустить скрипт «{0}» на сервере «{1}» ({2})?\n\nОн откроется в новой вкладке терминала.",
            "Run script \"{0}\" on server \"{1}\" ({2})?\n\nIt opens in a new terminal tab."),
        ["Scripts.Uploading"] = ("Загружаю «{0}» на {1}…", "Uploading \"{0}\" to {1}…"),
        ["Scripts.Started"] = ("Скрипт «{0}» запущен на {1}", "Script \"{0}\" started on {1}"),
        ["Scripts.Add"] = ("+ Скрипт", "+ Script"),
        ["Scripts.Duplicate"] = ("Копия", "Copy"),
        ["Scripts.Delete"] = ("Удалить", "Delete"),
        ["Scripts.Name"] = ("Название", "Name"),
        ["Scripts.OsFilter"] = ("Для ОС (ID из os-release)", "For OS (os-release ID)"),
        ["Scripts.OsFilterTip"] = ("Через запятую: debian, ubuntu, almalinux… Пусто — для любой ОС", "Comma separated: debian, ubuntu, almalinux… Empty — any OS"),
        ["Scripts.UseSudo"] = ("Запускать через sudo (если вход не под root)", "Run with sudo (when not logged in as root)"),
        ["Scripts.Save"] = ("Сохранить", "Save"),
        ["Scripts.NewName"] = ("Новый скрипт", "New script"),
        ["Scripts.DeleteConfirm"] = ("Удалить скрипт «{0}»?", "Delete script \"{0}\"?"),

        // ---------- backup ----------
        ["Backup.Title"] = ("Резервная копия", "Backup"),
        ["Backup.ToFolder"] = ("В папку на диске", "To a folder"),
        ["Backup.ToServer"] = ("На сервер по SSH (SFTP)", "To a server over SSH (SFTP)"),
        ["Backup.Browse"] = ("Обзор…", "Browse…"),
        ["Backup.ChooseFolder"] = ("Папка для резервных копий", "Backup folder"),
        ["Backup.Server"] = ("Сервер", "Server"),
        ["Backup.RemotePath"] = ("Папка на сервере (относительно домашней)", "Remote folder (relative to home)"),
        ["Backup.Keep"] = ("Хранить копий:", "Keep copies:"),
        ["Backup.AutoHours"] = ("Автоматически каждые N часов (0 — выкл.):", "Automatically every N hours (0 = off):"),
        ["Backup.Hint"] = ("Архив содержит всю папку data. vault.dat внутри зашифрован — для восстановления нужен мастер-пароль: распакуйте архив в папку data.",
            "The archive holds the whole data folder. vault.dat inside is encrypted — restoring needs the master password: unpack the archive into the data folder."),
        ["Backup.Never"] = ("Бэкап ещё не делался", "No backup yet"),
        ["Backup.Running"] = ("Создаю резервную копию…", "Creating a backup…"),
        ["Backup.Done"] = ("Резервная копия сохранена: {0}", "Backup saved: {0}"),
        ["Backup.ResultOk"] = ("Последний бэкап {0:g}: {1}", "Last backup {0:g}: {1}"),
        ["Backup.ResultFailed"] = ("Ошибка бэкапа {0:g}: {1}", "Backup failed {0:g}: {1}"),
        ["Backup.NotConfigured"] = ("Укажите, куда сохранять резервные копии (Настройки → Резервное копирование).",
            "Choose where to store backups (Settings → Backup)."),
        ["Backup.ServerMissing"] = ("Сервер для бэкапа не найден в хранилище", "The backup server is not in the vault"),
        ["Backup.AutoFailed"] = ("Автоматический бэкап не удался:", "Automatic backup failed:"),

        // ---------- settings ----------
        ["Settings.Interface"] = ("Интерфейс", "Interface"),
        ["Settings.Language"] = ("Язык / Language:", "Language / Язык:"),
        ["Settings.Startup"] = ("Запуск и трей", "Startup and tray"),
        ["Settings.AutostartBox"] = ("Запускать вместе с Windows (сразу в трей, заблокированным)", "Start with Windows (in the tray, locked)"),
        ["Settings.CloseToTray"] = ("Кнопка закрытия сворачивает в трей (агент продолжает работать)", "The close button hides to the tray (the agent keeps running)"),
        ["Settings.Autostart.Title"] = ("Автозапуск", "Autostart"),
        ["Settings.Autostart.Failed"] = ("Не удалось изменить автозапуск:", "Could not change autostart:"),
        ["Settings.Security"] = ("Безопасность", "Security"),
        ["Settings.AutoLock"] = ("Автоблокировка после простоя ПК, минут (0 — никогда):", "Lock after PC idle time, minutes (0 = never):"),
        ["Settings.LockOnWinL"] = ("Блокировать при блокировке Windows (Win+L)", "Lock when Windows locks (Win+L)"),
        ["Settings.UnlockOnAgent"] = ("Показывать окно разблокировки, когда ssh / git / VS Code обращаются к агенту",
            "Show the unlock window when ssh / git / VS Code ask the agent"),
        ["Settings.ChangePassword"] = ("Сменить мастер-пароль…", "Change master password…"),
        ["Settings.Monitoring"] = ("Мониторинг и сведения о серверах", "Monitoring and server information"),
        ["Settings.MonitorInterval"] = ("Проверять доступность каждые, минут (0 — выкл.):", "Check availability every, minutes (0 = off):"),
        ["Settings.MonitorHint"] = ("Проверяется TCP-подключение к SSH-порту и ответ sshd. Для отдельного сервера интервал меняется в его настройках.",
            "A TCP connection to the SSH port and the sshd greeting are checked. Per-server intervals are set in the server editor."),
        ["Settings.CollectMetrics"] = ("После проверки заходить по SSH и снимать загрузку CPU, памяти и диска", "After a check, log in over SSH to read CPU, memory and disk usage"),
        ["Settings.NotifyDown"] = ("Уведомлять в трее, когда сервер становится недоступен", "Notify in the tray when a server goes down"),
        ["Settings.AutoInventory"] = ("Определять ОС, Docker-контейнеры, сервисы и пробросы автоматически", "Detect OS, Docker containers, services and forwards automatically"),
        ["Settings.GeoIp"] = ("Определять страну и город сервера (GeoIP)", "Detect server country and city (GeoIP)"),
        ["Settings.GeoIpHint"] = ("IP-адреса серверов отправляются в онлайн-сервис ipwho.is (запасной — ip-api.com); результат кэшируется на 30 дней.",
            "Server IP addresses are sent to the online service ipwho.is (fallback ip-api.com); results are cached for 30 days."),
        ["Settings.Scripts"] = ("Установочные скрипты", "Install scripts"),
        ["Settings.ScriptsHint"] = ("Вставьте скрипт (bash) — он появится в меню сервера «Установить». Выполняется в терминале, поэтому вопросы установщика работают. Доступны переменные SSHM_SERVER_NAME и SSHM_HOST. Скрипты хранятся в зашифрованном хранилище.",
            "Paste a (bash) script — it appears in the server menu \"Install\". It runs in a terminal, so installer prompts work. SSHM_SERVER_NAME and SSHM_HOST are set. Scripts are stored in the encrypted vault."),
        ["Settings.Backup"] = ("Резервное копирование", "Backup"),
        ["Settings.Terminal"] = ("Терминал", "Terminal"),
        ["Settings.WtTab"] = ("Windows Terminal — новая вкладка", "Windows Terminal — new tab"),
        ["Settings.WtWindow"] = ("Windows Terminal — новое окно", "Windows Terminal — new window"),
        ["Settings.Console"] = ("Обычное окно консоли", "Plain console window"),
        ["Settings.WtFound"] = ("Windows Terminal найден:", "Windows Terminal found:"),
        ["Settings.WtMissing"] = ("Windows Terminal не найден — сессии будут открываться в обычном окне консоли",
            "Windows Terminal not found — sessions open in a plain console window"),
        ["Settings.WtProfile"] = ("Профиль Windows Terminal (необязательно)", "Windows Terminal profile (optional)"),
        ["Settings.SshPath"] = ("Путь к ssh.exe (пусто — системный OpenSSH)", "Path to ssh.exe (empty = system OpenSSH)"),
        ["Settings.SshUsed"] = ("Используется:", "In use:"),
        ["Settings.AliveInterval"] = ("ServerAliveInterval, секунд (0 — выкл.):", "ServerAliveInterval, seconds (0 = off):"),
        ["Settings.HelperInfo"] = ("Из любого терминала: \"{0}\" <имя сервера>  (добавьте папку в PATH, чтобы писать просто sshm <имя>)",
            "From any terminal: \"{0}\" <server name>  (add the folder to PATH to type just sshm <name>)"),
        ["Settings.Data"] = ("Данные", "Data"),
        ["Settings.DataHint"] = ("vault.dat — зашифрованное хранилище, backups — его предыдущие версии, known_hosts — ключи серверов, pub — публичные ключи. Для резервной копии используйте раздел выше или скопируйте всю папку data и помните мастер-пароль.",
            "vault.dat is the encrypted vault, backups holds its previous versions, known_hosts the server keys, pub the public keys. Use the backup section above or copy the whole data folder — and remember the master password."),
    };
}
