namespace SshManager.Core.Localization;

/// <summary>
/// Translations, side by side so a missing language is impossible. Format placeholders ({0}) must match in both.
/// </summary>
internal static class Strings
{
    public static readonly Dictionary<string, (string Ru, string En)> Table = new()
    {
        // ---------- common ----------
        ["Common.Save"] = ("Сохранить", "Save"),
        ["Common.Cancel"] = ("Отмена", "Cancel"),
        ["Common.Close"] = ("Закрыть", "Close"),
        ["Common.Error"] = ("ОШИБКА:", "ERROR:"),
        ["App.ErrorTitle"] = ("SSH Manager — ошибка", "SSH Manager — error"),
        ["Lang.System"] = ("Как в Windows", "Windows default"),

        // ---------- menu ----------
        ["Menu.File"] = ("_Файл", "_File"),
        ["Menu.NewServer"] = ("Новый сервер…", "New server…"),
        ["Menu.BackupNow"] = ("Сделать бэкап сейчас", "Back up now"),
        ["Menu.OpenDataFolder"] = ("Открыть папку данных", "Open data folder"),
        ["Menu.Lock"] = ("Заблокировать", "Lock"),
        ["Menu.Exit"] = ("Выход", "Exit"),
        ["Menu.View"] = ("_Вид", "_View"),
        ["Menu.ExpandAll"] = ("Развернуть все группы", "Expand all groups"),
        ["Menu.CollapseAll"] = ("Свернуть все", "Collapse all"),
        ["Menu.RefreshAll"] = ("Обновить информацию о серверах", "Refresh server information"),
        ["Menu.Language"] = ("_Язык (Language)", "_Language (Язык)"),
        ["Menu.Help"] = ("_Справка", "_Help"),
        ["Menu.About"] = ("О программе", "About"),
        ["About.Title"] = ("О программе", "About"),
        ["About.Text"] = ("SSH Manager {0}\n\nСерверы, ключи, SSH-агент, терминал, файлы, мониторинг и пробросы портов.\n\nЛицензия MIT · github.com/nickolsky/ssh-manager\n\nПапка данных:\n{1}",
            "SSH Manager {0}\n\nServers, keys, SSH agent, terminal, files, monitoring and port forwarding.\n\nMIT License · github.com/nickolsky/ssh-manager\n\nData folder:\n{1}"),

        // ---------- tabs / main ----------
        ["Tab.Servers"] = ("Серверы", "Servers"),
        ["Tab.Keys"] = ("Ключи", "Keys"),
        ["Tab.Settings"] = ("Настройки", "Settings"),
        ["Main.Connect"] = ("Подключиться", "Connect"),
        ["Main.AddServer"] = ("+ Сервер", "+ Server"),
        ["Main.Edit"] = ("Изменить", "Edit"),
        ["Main.SetupKey"] = ("Настроить вход по ключу", "Set up key login"),
        ["Main.SetupKeyTip"] = ("Войти по паролю, установить ключ в authorized_keys и переключить сервер на ключ",
            "Log in with the password, install a key into authorized_keys and switch the server to key login"),
        ["Main.Test"] = ("Проверить", "Test"),
        ["Main.PortForwards"] = ("Пробросы портов", "Port forwards"),
        ["Main.RefreshAllTip"] = ("Обновить ОС, регион, контейнеры и статус всех серверов (F5)",
            "Refresh OS, location, containers and status of all servers (F5)"),
        ["Main.RefreshingAll"] = ("Обновляю информацию о серверах…", "Refreshing server information…"),
        ["Main.Search"] = ("Поиск:", "Search:"),
        ["Main.SearchTip"] = ("Поиск по названию, адресу, группе, заметкам, ОС, региону, контейнерам (Ctrl+F)",
            "Search by name, address, group, notes, OS, location, containers (Ctrl+F)"),
        ["Main.Lock"] = ("Заблокировать", "Lock"),
        ["Main.Summary"] = ("Серверов: {0} (онлайн {1}, недоступно {2})   Ключей: {3}",
            "Servers: {0} ({1} online, {2} down)   Keys: {3}"),
        ["Main.SessionOpened"] = ("Открыта сессия: {0}", "Session opened: {0}"),
        ["Main.SessionFailed"] = ("Не удалось открыть сессию", "Could not open the session"),
        ["Main.CopySuffix"] = (" (копия)", " (copy)"),
        ["Main.DeleteServerConfirm"] = ("Удалить сервер «{0}» ({1})?\nКлючи останутся в хранилище.",
            "Delete server \"{0}\" ({1})?\nKeys stay in the vault."),
        ["Main.CommandCopied"] = ("Команда ssh скопирована в буфер обмена", "ssh command copied to the clipboard"),
        ["Main.Testing"] = ("Проверка подключения к {0}…", "Testing connection to {0}…"),
        ["Main.TestOkStatus"] = ("{0}: подключение успешно", "{0}: connection OK"),
        ["Main.TestFailedStatus"] = ("{0}: ошибка подключения", "{0}: connection failed"),
        ["Main.TestTitle"] = ("Проверка подключения", "Connection test"),
        ["Main.TestOk"] = ("Подключение к {0} успешно.\n\n{1}", "Connected to {0} successfully.\n\n{1}"),
        ["Main.TestFailed"] = ("Не удалось подключиться к {0}:\n\n{1}", "Could not connect to {0}:\n\n{1}"),
        ["Agent.NotRunning"] = ("Агент не запущен (pipe занят другим приложением)", "Agent is not running (the pipe is used by another app)"),
        ["Agent.Default"] = ("Агент: \\\\.\\pipe\\{0} — доступен для ssh, git, VS Code", "Agent: \\\\.\\pipe\\{0} — available to ssh, git, VS Code"),
        ["Agent.Fallback"] = ("Агент: \\\\.\\pipe\\{0} (стандартный pipe занят; для внешних клиентов задайте SSH_AUTH_SOCK)",
            "Agent: \\\\.\\pipe\\{0} (the standard pipe is busy; set SSH_AUTH_SOCK for external clients)"),

        // ---------- columns ----------
        ["Col.Name"] = ("Название", "Name"),
        ["Col.Address"] = ("Адрес", "Address"),
        ["Col.Os"] = ("ОС", "OS"),
        ["Col.Cpu"] = ("CPU", "CPU"),
        ["Col.Mem"] = ("Память", "Memory"),
        ["Col.Ports"] = ("Порты", "Ports"),
        ["Col.Region"] = ("Регион", "Location"),
        ["Col.Forwards"] = ("Пробросы", "Forwards"),
        ["Col.Auth"] = ("Вход", "Login"),
        ["Col.LastConnected"] = ("Последнее подключение", "Last connected"),
        ["Col.Notes"] = ("Заметки", "Notes"),
        ["Col.Disk"] = ("Диск", "Disk"),
        ["Col.Uptime"] = ("Аптайм (сутки · неделя · месяц)", "Uptime (day · week · month)"),
        ["Auth.Password"] = ("Пароль", "Password"),
        ["Auth.KeyMissing"] = ("ключ не найден", "key not found"),

        // ---------- tree ----------
        ["Tree.GroupOffline"] = ("⚠ недоступно: {0}", "⚠ {0} down"),
        ["Tree.Updated"] = ("Обновлено: {0}", "Updated: {0}"),
        ["Tree.Error"] = ("Ошибка:", "Error:"),
        ["Tree.Isp"] = ("Провайдер:", "ISP:"),
        ["Tree.Loading"] = ("Загрузка информации с сервера…", "Loading information from the server…"),
        ["Tree.NoData"] = ("Нет данных — «Обновить информацию» в контекстном меню", "No data yet — use \"Refresh info\" in the context menu"),
        ["Tree.Docker"] = ("Docker ({0}/{1})", "Docker ({0}/{1})"),
        ["Tree.NoContainers"] = ("Контейнеров нет", "No containers"),
        ["Tree.Services"] = ("Сервисы ({0}/{1})", "Services ({0}/{1})"),
        ["Tree.ForwardsSection"] = ("Пробросы ({0})", "Forwards ({0})"),
        ["Tree.PortsSection"] = ("Порты ({0}/{1})", "Ports ({0}/{1})"),
        ["Tree.AttributesSection"] = ("Результаты скриптов ({0})", "Script results ({0})"),
        ["Attr.Tip"] = ("Скрипт: {0}\nОбновлено: {1}", "Script: {0}\nUpdated: {1}"),
        ["Attr.Copied"] = ("Скопировано: {0}", "Copied: {0}"),
        ["Attr.DeleteConfirm"] = ("Удалить «{0}» у сервера «{1}»?", "Remove \"{0}\" from server \"{1}\"?"),
        ["Port.Open"] = ("открыт", "open"),
        ["Port.Closed"] = ("НЕ ОТВЕЧАЕТ", "NOT ANSWERING"),
        ["Port.Monitored"] = ("мониторинг, ещё не проверен", "monitored, not checked yet"),
        ["Port.NotMonitored"] = ("не отслеживается", "not monitored"),
        ["Port.LocalOnly"] = ("только localhost — снаружи не проверить", "localhost only — cannot be checked from outside"),
        ["Port.OpenTip"] = ("Порт {0} открыт, {1} мс (проверка в {2})", "Port {0} is open, {1} ms (checked at {2})"),
        ["Port.ClosedTip"] = ("Порт {0} не отвечает (проверка в {1})\n{2}", "Port {0} does not answer (checked at {1})\n{2}"),
        ["Port.NotCheckedTip"] = ("Порт {0} ещё не проверялся", "Port {0} has not been checked yet"),
        ["Port.MonitorOn"] = ("Порт {0} на {1} теперь отслеживается", "Port {0} on {1} is now monitored"),
        ["Port.MonitorOff"] = ("Порт {0} на {1} больше не отслеживается", "Port {0} on {1} is no longer monitored"),
        ["PortMon.Title"] = ("Мониторинг портов", "Port monitoring"),
        ["PortMon.Hint"] = ("Отмеченные TCP-порты проверяются вместе с сервером: если порт перестал отвечать, сервер помечается жёлтым и приходит уведомление. Для порта с пробросом проверяется вся цепочка до целевого сервера.",
            "Checked TCP ports are tested together with the server: when a port stops answering, the server turns yellow and you get a notification. For a forwarded port the whole chain to the target server is tested."),
        ["PortMon.Monitor"] = ("Следить", "Monitor"),
        ["PortMon.Port"] = ("Порт", "Port"),
        ["PortMon.Name"] = ("Что это", "What it is"),
        ["PortMon.Source"] = ("Источник", "Source"),
        ["PortMon.Add"] = ("+ Порт", "+ Port"),
        ["PortMon.Detect"] = ("Найти порты на сервере", "Detect ports on the server"),
        ["PortMon.SourceListening"] = ("слушает: {0}", "listening: {0}"),
        ["PortMon.SourceLocal"] = ("только localhost: {0}", "localhost only: {0}"),
        ["PortMon.SourceForward"] = ("проброс → {0}:{1}", "forward → {0}:{1}"),
        ["PortMon.SourceManual"] = ("добавлен вручную", "added manually"),
        ["Tree.Incoming"] = ("← с {0}: {1} {2} → :{3}", "← from {0}: {1} {2} → :{3}"),

        // ---------- context menu ----------
        ["Ctx.Connect"] = ("Подключиться", "Connect"),
        ["Ctx.Install"] = ("Установить", "Install"),
        ["Ctx.PortForwards"] = ("Пробросы портов…", "Port forwards…"),
        ["Ctx.RefreshInfo"] = ("Обновить информацию", "Refresh info"),
        ["Ctx.CheckNow"] = ("Проверить доступность сейчас", "Check availability now"),
        ["Ctx.UptimeHistory"] = ("История доступности…", "Uptime history…"),
        ["Ctx.InstallDocker"] = ("Установить Docker…", "Install Docker…"),
        ["Ctx.ContainerStart"] = ("Запустить", "Start"),
        ["Ctx.ContainerStop"] = ("Остановить…", "Stop…"),
        ["Ctx.ContainerAutostart"] = ("Автозапуск", "Autostart"),
        ["Ctx.ContainerRemove"] = ("Удалить…", "Remove…"),
        ["Container.Title"] = ("Контейнер", "Container"),
        ["Service.Title"] = ("Сервис", "Service"),
        ["Service.AutostartOn"] = ("Запускать при загрузке (enable)", "Start on boot (enable)"),
        ["Service.AutostartOff"] = ("Не запускать при загрузке (disable)", "Do not start on boot (disable)"),
        ["Service.EnabledTip"] = ("Автозапуск: {0}", "On boot: {0}"),
        ["Service.Starting"] = ("Запускаю {0}…", "Starting {0}…"),
        ["Service.Started"] = ("{0} запущен", "{0} started"),
        ["Service.Stopping"] = ("Останавливаю {0}…", "Stopping {0}…"),
        ["Service.Stopped"] = ("{0} остановлен", "{0} stopped"),
        ["Service.Restarting"] = ("Перезапускаю {0}…", "Restarting {0}…"),
        ["Service.Restarted"] = ("{0} перезапущен", "{0} restarted"),
        ["Service.Enabling"] = ("Включаю автозапуск {0}…", "Enabling {0} on boot…"),
        ["Service.EnabledDone"] = ("{0} будет запускаться при загрузке", "{0} now starts on boot"),
        ["Service.Disabling"] = ("Выключаю автозапуск {0}…", "Disabling {0} on boot…"),
        ["Service.DisabledDone"] = ("{0} больше не запускается при загрузке", "{0} no longer starts on boot"),
        ["Service.StopConfirm"] = ("Остановить {0} ({1}.service) на «{2}»?", "Stop {0} ({1}.service) on \"{2}\"?"),
        ["Service.DisableConfirm"] = ("Выключить автозапуск {0} на «{1}»? Сейчас сервис продолжит работать, но после перезагрузки не запустится.",
            "Disable {0} on boot on \"{1}\"? It keeps running now but will not start after a reboot."),
        ["Service.SshWarning"] = ("ВНИМАНИЕ: это SSH-сервер. Без него к машине будет не подключиться — ни из программы, ни вручную.",
            "WARNING: this is the SSH server. Without it you cannot connect to the machine, neither from the app nor by hand."),
        ["Service.SshRestartConfirm"] = ("Перезапустить SSH-сервер? Если конфигурация sshd сломана, он может не подняться и доступ пропадёт.",
            "Restart the SSH server? If the sshd config is broken it may not come back and you lose access."),
        ["Container.PolicyUnlessStopped"] = ("Да, если не остановлен вручную (unless-stopped)", "Yes, unless stopped by hand (unless-stopped)"),
        ["Container.PolicyAlways"] = ("Всегда (always)", "Always (always)"),
        ["Container.PolicyOnFailure"] = ("Только после сбоя (on-failure)", "Only after a crash (on-failure)"),
        ["Container.PolicyNo"] = ("Нет (no)", "No (no)"),
        ["Container.PolicyTip"] = ("Автозапуск: {0}", "Restart policy: {0}"),
        ["Container.ComposeTip"] = ("Compose-проект {0} ({1})", "Compose project {0} ({1})"),
        ["Container.Starting"] = ("Запускаю {0}…", "Starting {0}…"),
        ["Container.Started"] = ("Контейнер {0} запущен", "Container {0} started"),
        ["Container.Stopping"] = ("Останавливаю {0}…", "Stopping {0}…"),
        ["Container.Stopped"] = ("Контейнер {0} остановлен", "Container {0} stopped"),
        ["Container.Restarting"] = ("Перезапускаю {0}…", "Restarting {0}…"),
        ["Container.Restarted"] = ("Контейнер {0} перезапущен", "Container {0} restarted"),
        ["Container.Removing"] = ("Удаляю {0}…", "Removing {0}…"),
        ["Container.Removed"] = ("{0} удалён", "{0} removed"),
        ["Container.Updating"] = ("Меняю автозапуск {0}…", "Changing the restart policy of {0}…"),
        ["Container.Updated"] = ("Автозапуск {0} изменён", "Restart policy of {0} changed"),
        ["Container.Failed"] = ("Не получилось ({0}):\n{1}", "Failed ({0}):\n{1}"),
        ["Container.StopConfirm"] = ("Остановить контейнер «{0}» на «{1}»?", "Stop container \"{0}\" on \"{1}\"?"),
        ["Container.StopAutostartHint"] = ("Остановленный вручную контейнер с автозапуском unless-stopped не поднимется после перезагрузки, с always — поднимется.",
            "A container stopped by hand does not come back after a reboot with unless-stopped; with always it does."),
        ["Container.ComposePolicyNote"] = ("Контейнер создан docker compose (проект «{0}»). Изменение действует до следующего docker compose up — тот возьмёт restart: из docker-compose.yml. Продолжить?",
            "The container was created by docker compose (project \"{0}\"). The change lasts until the next docker compose up, which applies restart: from docker-compose.yml. Continue?"),
        ["Container.RemoveTitle"] = ("Удаление контейнера", "Remove container"),
        ["Container.RemoveHeader"] = ("Удалить «{0}» с сервера «{1}»?", "Remove \"{0}\" from server \"{1}\"?"),
        ["Container.RemoveInfo"] = ("Образ {0}, {1}", "Image {0}, {1}"),
        ["Container.RemoveInfoCompose"] = ("Образ {0}, {1}\nCompose-проект «{2}», папка {3}", "Image {0}, {1}\nCompose project \"{2}\", folder {3}"),
        ["Container.RemoveOnly"] = ("Только контейнер «{0}» (docker rm -f)", "Only the container \"{0}\" (docker rm -f)"),
        ["Container.RemoveProject"] = ("Весь compose-проект «{0}» (docker compose down)", "The whole compose project \"{0}\" (docker compose down)"),
        ["Container.RemoveVolumes"] = ("Удалить и его анонимные тома", "Also remove its anonymous volumes"),
        ["Container.RemoveVolumesProject"] = ("Удалить именованные тома проекта (данные в volumes)", "Also remove the project's named volumes (data in volumes)"),
        ["Container.RemoveImage"] = ("Удалить образ, если он больше не используется", "Remove the image if nothing else uses it"),
        ["Container.RemoveFolder"] = ("Удалить папку проекта {0} (docker-compose.yml, .env и данные в ней)", "Delete the project folder {0} (docker-compose.yml, .env and data in it)"),
        ["Container.RemoveButton"] = ("Удалить", "Remove"),
        ["Container.RemoveWarning"] = ("Удаление нельзя отменить. Данные в папках на сервере (bind mount) остаются, если не удалить папку проекта.",
            "This cannot be undone. Data in server folders (bind mounts) stays unless the project folder is deleted."),
        ["Ctx.CopyValue"] = ("Копировать значение", "Copy value"),
        ["Ctx.DeleteAttribute"] = ("Удалить", "Remove"),
        ["Ctx.Edit"] = ("Изменить…", "Edit…"),
        ["Ctx.Duplicate"] = ("Дублировать…", "Duplicate…"),
        ["Ctx.CopyCommand"] = ("Копировать команду ssh", "Copy ssh command"),
        ["Ctx.SetupKey"] = ("Настроить вход по ключу…", "Set up key login…"),
        ["Ctx.Test"] = ("Проверить подключение", "Test connection"),
        ["Ctx.Delete"] = ("Удалить", "Delete"),
        ["Ctx.ContainerLogs"] = ("Логи контейнера", "Container logs"),
        ["Ctx.ContainerRestart"] = ("Перезапустить контейнер", "Restart container"),
        ["Ctx.ServiceStatus"] = ("Статус сервиса", "Service status"),
        ["Ctx.ServiceLogs"] = ("Журнал сервиса", "Service log"),
        ["Ctx.ServiceRestart"] = ("Перезапустить сервис", "Restart service"),
        ["Ctx.MonitorPort"] = ("Следить за этим портом", "Monitor this port"),
        ["Ctx.UnmonitorPort"] = ("Не следить за этим портом", "Stop monitoring this port"),
        ["Ctx.PortMonitor"] = ("Мониторинг портов…", "Port monitoring…"),
        ["Ctx.AddServer"] = ("Добавить сервер в группу…", "Add server to this group…"),

        // ---------- health / metrics ----------
        ["Health.OnlineTip"] = ("Доступен, {0} мс (проверка в {1})", "Online, {0} ms (checked at {1})"),
        ["Health.OfflineTip"] = ("Недоступен (проверка в {0})\n{1}", "Down (checked at {0})\n{1}"),
        ["Health.SshDownPortUp"] = ("SSH не отвечает ({0}), но отслеживаемый порт открыт — сервер считается доступным",
            "SSH does not answer ({0}) but a monitored port is open, so the server counts as up"),
        ["Health.Checking"] = ("Проверка…", "Checking…"),
        ["Health.Disabled"] = ("Мониторинг выключен для этого сервера", "Monitoring is off for this server"),
        ["Health.JumpHost"] = ("Через jump-хост — не проверяется", "Behind a jump host — not checked"),
        ["Health.Unknown"] = ("Ещё не проверялся", "Not checked yet"),
        ["Health.NoBanner"] = ("Порт открыт, но SSH не ответил", "Port is open but SSH did not answer"),
        ["Health.Timeout"] = ("Нет ответа (таймаут)", "No answer (timeout)"),
        ["Health.DownTitle"] = ("Сервер недоступен", "Server is down"),
        ["Health.DownText"] = ("{0}: {1}", "{0}: {1}"),
        ["Health.PortsDown"] = ("Не отвечают порты: {0}", "Ports not answering: {0}"),
        ["Health.PortDownTitle"] = ("Порт недоступен", "Port is down"),
        ["Health.PortDownText"] = ("{0}: порт {1} не отвечает\n{2}", "{0}: port {1} does not answer\n{2}"),
        ["Metrics.Cpu"] = ("CPU: {0:0}% (load {1:0.00}, ядер: {2})", "CPU: {0:0}% (load {1:0.00}, {2} cores)"),
        ["Metrics.Mem"] = ("Память: {0} из {1} ({2:0}%)", "Memory: {0} of {1} ({2:0}%)"),
        ["Metrics.Disk"] = ("Диск /: {0} из {1} ({2:0}%)", "Disk /: {0} of {1} ({2:0}%)"),
        ["Metrics.DiskFree"] = ("свободно {0}", "{0} free"),
        ["Uptime.Tip"] = ("Доступность за сутки: {0}\nза неделю: {1}\nза 30 дней: {2}\n\nПодробнее: правый клик → «История доступности»",
            "Uptime for the day: {0}\nweek: {1}\n30 days: {2}\n\nDetails: right click → \"Uptime history\""),
        ["Uptime.Title"] = ("История доступности", "Uptime history"),
        ["Uptime.WindowTitle"] = ("История доступности — {0}", "Uptime history — {0}"),
        ["Uptime.Period24h"] = ("За 24 часа", "Last 24 hours"),
        ["Uptime.Period7d"] = ("За 7 дней", "Last 7 days"),
        ["Uptime.Period30d"] = ("За 30 дней", "Last 30 days"),
        ["Uptime.Period90d"] = ("За 90 дней", "Last 90 days"),
        ["Uptime.Period365d"] = ("За год", "Last year"),
        ["Uptime.TileUptime"] = ("Доступность", "Uptime"),
        ["Uptime.TileOutages"] = ("Отключений", "Outages"),
        ["Uptime.TileDowntime"] = ("Простой", "Downtime"),
        ["Uptime.TileLatency"] = ("Средняя задержка", "Average latency"),
        ["Uptime.LegendUp"] = ("доступен", "up"),
        ["Uptime.LegendDegraded"] = ("только порт (SSH нет)", "port only (no SSH)"),
        ["Uptime.LegendDown"] = ("недоступен", "down"),
        ["Uptime.LegendNoData"] = ("нет данных", "no data"),
        ["Uptime.Availability"] = ("Доступность", "Availability"),
        ["Uptime.Latency"] = ("Задержка подключения, мс", "Connect latency, ms"),
        ["Uptime.Outages"] = ("Отключения ({0})", "Outages ({0})"),
        ["Uptime.OutageFrom"] = ("Начало", "Start"),
        ["Uptime.OutageTo"] = ("Конец", "End"),
        ["Uptime.OutageDuration"] = ("Длительность", "Duration"),
        ["Uptime.Ongoing"] = ("продолжается", "ongoing"),
        ["Uptime.Ms"] = ("{0:0} мс", "{0:0} ms"),
        ["Uptime.Sec"] = ("{0} с", "{0} s"),
        ["Uptime.Min"] = ("{0} мин", "{0} min"),
        ["Uptime.HourMin"] = ("{0} ч {1} мин", "{0} h {1} min"),
        ["Uptime.DayHour"] = ("{0} д {1} ч", "{0} d {1} h"),
        ["Uptime.BucketUp"] = ("Доступен: {0}", "Up: {0}"),
        ["Uptime.BucketDegraded"] = ("из них только порт, без SSH: {0}", "of it port only, no SSH: {0}"),
        ["Uptime.BucketLatency"] = ("Задержка: {0:0} мс", "Latency: {0:0} ms"),
        ["Uptime.NoData"] = ("Нет данных (программа не работала или мониторинг выключен)", "No data (the app was not running or monitoring was off)"),
        ["Uptime.Empty"] = ("Пока нет проверок за этот период. История пишется при каждой проверке доступности.",
            "No checks in this period yet. History is written on every availability check."),
        ["Uptime.Footer"] = ("Проверок за период: {0}, первая: {1}. Промежутки, когда программа не работала, не учитываются.",
            "Checks in the period: {0}, first: {1}. Time the app was not running is not counted."),
        ["Metrics.Uptime"] = ("Аптайм: {0} д {1} ч {2} мин", "Uptime: {0} d {1} h {2} min"),
        ["Metrics.Collected"] = ("Снято в {0}", "Collected at {0}"),

        // ---------- host keys / ssh ----------
        ["HostKey.Title"] = ("Проверка ключа сервера", "Server key check"),
        ["HostKey.Changed"] = ("ВНИМАНИЕ: ключ сервера {0} ИЗМЕНИЛСЯ!\n\nЭто может означать переустановку сервера или атаку «человек посередине».\n\nНовый ключ: {1}\n{2}\n\nЗаменить сохранённый ключ и продолжить?",
            "WARNING: the key of server {0} HAS CHANGED!\n\nThe server may have been reinstalled — or this is a man-in-the-middle attack.\n\nNew key: {1}\n{2}\n\nReplace the stored key and continue?"),
        ["HostKey.New"] = ("Первое подключение к {0}.\n\nКлюч сервера: {1}\n{2}\n\nДоверять этому серверу и сохранить его ключ?",
            "First connection to {0}.\n\nServer key: {1}\n{2}\n\nTrust this server and save its key?"),
        ["Ssh.HostKeyNotTrusted"] = ("Ключ сервера {0} ещё не подтверждён — подключитесь к нему один раз вручную",
            "The key of server {0} is not confirmed yet — connect to it once manually"),
        ["Ssh.CommandTimeout"] = ("Команда на сервере не завершилась вовремя", "The command on the server timed out"),
        ["Launch.NoKey"] = ("У сервера «{0}» не выбран ключ", "No key selected for server \"{0}\""),
        ["Launch.NoPassword"] = ("У сервера «{0}» не сохранён пароль", "No password saved for server \"{0}\""),
        ["Inventory.JumpHost"] = ("Серверы за jump-хостом не опрашиваются", "Servers behind a jump host are not queried"),
        ["Inventory.Failed"] = ("Не удалось получить информацию:", "Could not collect information:"),

        // ---------- vault / ipc / cli ----------
        ["Vault.Exists"] = ("Хранилище уже существует", "The vault already exists"),
        ["Vault.Locked"] = ("Хранилище заблокировано", "The vault is locked"),
        ["Vault.Corrupt"] = ("Файл хранилища повреждён или имеет неизвестный формат", "The vault file is damaged or has an unknown format"),
        ["Vault.WrongPassword"] = ("Неверный мастер-пароль", "Wrong master password"),
        ["Key.UnsupportedType"] = ("Тип ключа {0} не поддерживается. Поддерживаются Ed25519 и RSA.", "Key type {0} is not supported. Ed25519 and RSA are."),
        ["Ipc.Closed"] = ("SSH Manager закрыл соединение", "SSH Manager closed the connection"),
        ["Ipc.Empty"] = ("Пустой ответ", "Empty response"),
        ["Ipc.NoPassword"] = ("Нет пароля", "No password"),
        ["Ipc.UnknownOp"] = ("Неизвестная команда {0}", "Unknown command {0}"),
        ["Ipc.ServerNotFound"] = ("Сервер «{0}» не найден (sshm list — список)", "Server \"{0}\" not found (sshm list shows all)"),
        ["Ipc.ServerAmbiguous"] = ("Подходит несколько серверов:", "Several servers match:"),
        ["Cli.Help"] = ("SSH Manager — консольный помощник\n  sshm <имя сервера|хост>   подключиться к сохранённому серверу в этом окне\n  sshm list                 список серверов",
            "SSH Manager — console helper\n  sshm <server name|host>   connect to a saved server in this window\n  sshm list                 list servers"),
        ["Cli.SessionNotFound"] = ("сессия не найдена или устарела", "session not found or expired"),
        ["Cli.ConnectFailed"] = ("не удалось подключиться", "could not connect"),
        ["Cli.Starting"] = ("запускаю SSH Manager…", "starting SSH Manager…"),
        ["Cli.NotResponding"] = ("SSH Manager не отвечает", "SSH Manager is not responding"),
        ["Cli.NotRunning"] = ("SSH Manager не запущен", "SSH Manager is not running"),
        ["Cli.NewHostTitle"] = ("SSH Manager — новый сервер", "SSH Manager — new server"),
        ["Cli.PasswordRejected"] = ("SSH Manager: сохранённый пароль не подошёл или сессия устарела.", "SSH Manager: the saved password was rejected or the session expired."),
        ["Cli.NoPassword"] = ("SSH Manager не запущен — пароль недоступен.", "SSH Manager is not running — no password available."),
        ["Cli.PressKey"] = ("Нажмите любую клавишу, чтобы закрыть окно…", "Press any key to close this window…"),

        // ---------- tray ----------
        ["Tray.StartedLocked"] = ("Работает в трее и заблокирован. Щёлкните, чтобы разблокировать.", "Running in the tray, locked. Click to unlock."),
        ["Tray.AgentNotRunning"] = ("не запущен", "not running"),
        ["Tray.Unlocked"] = ("разблокирован", "unlocked"),
        ["Tray.Locked"] = ("заблокирован", "locked"),
        ["Tray.Agent"] = ("Агент:", "Agent:"),
        ["Tray.Open"] = ("Открыть SSH Manager", "Open SSH Manager"),
        ["Tray.Connect"] = ("Подключиться", "Connect"),
        ["Tray.NoServers"] = ("(нет серверов)", "(no servers)"),
        ["Tray.Unlock"] = ("Разблокировать…", "Unlock…"),
        ["Tray.Lock"] = ("Заблокировать", "Lock"),
        ["Tray.Language"] = ("Язык (Language)", "Language (Язык)"),
        ["Tray.Exit"] = ("Выход", "Exit"),
        ["Tray.ByKey"] = ("Вход по ключу", "Key login"),
        ["Tray.ByPassword"] = ("Вход по паролю", "Password login"),

        // ---------- unlock / password ----------
        ["Unlock.Header"] = ("Разблокировать хранилище", "Unlock the vault"),
        ["Unlock.Subtitle"] = ("Введите мастер-пароль, чтобы открыть серверы и ключи.", "Enter the master password to open servers and keys."),
        ["Unlock.Password"] = ("Мастер-пароль", "Master password"),
        ["Unlock.Repeat"] = ("Повторите пароль", "Repeat the password"),
        ["Unlock.Autostart"] = ("Запускать вместе с Windows (в трее)", "Start with Windows (in the tray)"),
        ["Unlock.CryptoHint"] = ("Хранилище шифруется AES-256-GCM, ключ получается из пароля через Argon2id. Забытый мастер-пароль восстановить невозможно.",
            "The vault is encrypted with AES-256-GCM, the key is derived from the password with Argon2id. A forgotten master password cannot be recovered."),
        ["Unlock.Unlock"] = ("Разблокировать", "Unlock"),
        ["Unlock.CreateHeader"] = ("Создание хранилища", "Create the vault"),
        ["Unlock.CreateSubtitle"] = ("Придумайте мастер-пароль. Им шифруются все пароли серверов и приватные ключи в папке data.",
            "Choose a master password. It encrypts all server passwords and private keys in the data folder."),
        ["Unlock.Create"] = ("Создать", "Create"),
        ["Unlock.TooShort"] = ("Пароль должен быть не короче 8 символов.", "The password must be at least 8 characters."),
        ["Unlock.Mismatch"] = ("Пароли не совпадают.", "The passwords do not match."),
        ["ChangePwd.Title"] = ("Смена мастер-пароля", "Change master password"),
        ["ChangePwd.Current"] = ("Текущий пароль", "Current password"),
        ["ChangePwd.New"] = ("Новый пароль", "New password"),
        ["ChangePwd.Repeat"] = ("Повторите новый пароль", "Repeat the new password"),
        ["ChangePwd.Change"] = ("Сменить", "Change"),
        ["ChangePwd.TooShort"] = ("Новый пароль должен быть не короче 8 символов.", "The new password must be at least 8 characters."),
        ["ChangePwd.Done"] = ("Мастер-пароль изменён.", "The master password has been changed."),

        // ---------- server editor ----------
        ["Editor.Title"] = ("Сервер", "Server"),
        ["Editor.NewTitle"] = ("Новый сервер", "New server"),
        ["Editor.EditTitle"] = ("Сервер — {0}", "Server — {0}"),
        ["Editor.Name"] = ("Название", "Name"),
        ["Editor.Group"] = ("Группа", "Group"),
        ["Editor.GroupTip"] = ("Вложенные группы через «/», например VPN/Европа", "Nested groups with \"/\", e.g. VPN/Europe"),
        ["Editor.Host"] = ("IP-адрес или хост", "IP address or host"),
        ["Editor.Port"] = ("Порт", "Port"),
        ["Editor.User"] = ("Пользователь", "User"),
        ["Editor.Auth"] = ("Авторизация", "Authentication"),
        ["Editor.SshKey"] = ("SSH-ключ", "SSH key"),
        ["Editor.Show"] = ("Показать", "Show"),
        ["Editor.Key"] = ("Ключ", "Key"),
        ["Editor.NewKey"] = ("Новый ключ…", "New key…"),
        ["Editor.KeyHint"] = ("Пароль можно оставить сохранённым — он нужен кнопке «Настроить вход по ключу» и для sudo.",
            "You can keep the password saved — \"Set up key login\" and sudo use it."),
        ["Editor.Advanced"] = ("Дополнительно", "Advanced"),
        ["Editor.Jump"] = ("Jump-хост (ssh -J), например user@bastion:22", "Jump host (ssh -J), e.g. user@bastion:22"),
        ["Editor.ExtraArgs"] = ("Дополнительные аргументы ssh", "Extra ssh arguments"),
        ["Editor.Monitor"] = ("Проверка доступности, минут", "Availability check, minutes"),
        ["Editor.MonitorHint"] = ("Пусто — по умолчанию ({0} мин), 0 — не проверять", "Empty — default ({0} min), 0 — do not check"),
        ["Editor.Notes"] = ("Заметки", "Notes"),
        ["Editor.NeedHost"] = ("Укажите IP-адрес или имя хоста.", "Enter an IP address or host name."),
        ["Editor.BadPort"] = ("Порт должен быть числом от 1 до 65535.", "The port must be a number from 1 to 65535."),
        ["Editor.NeedUser"] = ("Укажите пользователя.", "Enter a user name."),
        ["Editor.NeedKey"] = ("Выберите ключ или создайте новый.", "Choose a key or create a new one."),
        ["Editor.BadMonitor"] = ("Интервал проверки — целое число минут (0 — выкл.).", "The check interval is a whole number of minutes (0 = off)."),

        // ---------- keys ----------
        ["Keys.Generate"] = ("+ Сгенерировать", "+ Generate"),
        ["Keys.Import"] = ("Импорт…", "Import…"),
        ["Keys.CopyPublic"] = ("Копировать публичный ключ", "Copy public key"),
        ["Keys.ExportPrivate"] = ("Экспорт приватного…", "Export private…"),
        ["Keys.Rename"] = ("Переименовать", "Rename"),
        ["Keys.Delete"] = ("Удалить", "Delete"),
        ["Keys.Type"] = ("Тип", "Type"),
        ["Keys.Fingerprint"] = ("Отпечаток", "Fingerprint"),
        ["Keys.Comment"] = ("Комментарий", "Comment"),
        ["Keys.Created"] = ("Создан", "Created"),
        ["Keys.Servers"] = ("Серверы", "Servers"),
        ["Keys.CreatedStatus"] = ("Ключ «{0}» создан", "Key \"{0}\" created"),
        ["Keys.ImportTitle"] = ("Импорт ключа", "Import key"),
        ["Keys.ImportFilter"] = ("Все файлы|*.*|PuTTY (*.ppk)|*.ppk|PEM (*.pem;*.key)|*.pem;*.key", "All files|*.*|PuTTY (*.ppk)|*.ppk|PEM (*.pem;*.key)|*.pem;*.key"),
        ["Keys.AlreadyExists"] = ("Этот ключ уже есть в хранилище.", "This key is already in the vault."),
        ["Keys.Imported"] = ("Ключ «{0}» импортирован ({1})", "Key \"{0}\" imported ({1})"),
        ["Keys.AskPassphrase"] = ("Ключ защищён паролем. Введите passphrase:", "The key is protected. Enter the passphrase:"),
        ["Keys.WrongPassphrase"] = ("Неверная passphrase. Попробуйте ещё раз:", "Wrong passphrase. Try again:"),
        ["Keys.ReadFailed"] = ("Не удалось прочитать ключ:", "Could not read the key:"),
        ["Keys.PublicCopied"] = ("Публичный ключ скопирован в буфер обмена", "Public key copied to the clipboard"),
        ["Keys.ExportWarning"] = ("Приватный ключ будет сохранён в файл БЕЗ шифрования.\nХраните этот файл в надёжном месте. Продолжить?",
            "The private key will be saved to a file WITHOUT encryption.\nKeep that file safe. Continue?"),
        ["Keys.ExportTitle"] = ("Экспорт приватного ключа", "Export private key"),
        ["Keys.Saved"] = ("Ключ сохранён: {0}", "Key saved: {0}"),
        ["Keys.RenameTitle"] = ("Переименовать ключ", "Rename key"),
        ["Keys.NewName"] = ("Новое название:", "New name:"),
        ["Keys.DeleteTitle"] = ("Удаление ключа", "Delete key"),
        ["Keys.InUse"] = ("Ключ используется серверами:\n{0}\n\nСначала переключите их на другой ключ или пароль.",
            "The key is used by:\n{0}\n\nSwitch those servers to another key or password first."),
        ["Keys.DeleteConfirm"] = ("Удалить ключ «{0}»?\n{1}\n\nЕсли у вас нет копии, восстановить его будет невозможно.",
            "Delete key \"{0}\"?\n{1}\n\nWithout a copy it cannot be recovered."),
        ["KeyGen.Title"] = ("Новый SSH-ключ", "New SSH key"),
        ["KeyGen.Comment"] = ("Комментарий (попадёт в authorized_keys)", "Comment (goes into authorized_keys)"),
        ["KeyGen.Ed25519"] = ("Ed25519 (рекомендуется)", "Ed25519 (recommended)"),
        ["KeyGen.Rsa"] = ("RSA 4096 (для старых серверов)", "RSA 4096 (for old servers)"),
        ["KeyGen.Generate"] = ("Сгенерировать", "Generate"),

        // ---------- key setup ----------
        ["KeySetup.Title"] = ("Настройка входа по ключу", "Key login setup"),
        ["KeySetup.Hint"] = ("Программа войдёт на сервер по сохранённому паролю, добавит публичный ключ в ~/.ssh/authorized_keys, проверит вход по ключу и переключит сервер на ключ. Вход по паролю на сервере не отключается.",
            "The app logs in with the saved password, adds the public key to ~/.ssh/authorized_keys, verifies key login and switches the server to the key. Password login on the server stays enabled."),
        ["KeySetup.Start"] = ("Настроить", "Set up"),
        ["KeySetup.GenerateNew"] = ("Сгенерировать новый ключ Ed25519", "Generate a new Ed25519 key"),
        ["KeySetup.Existing"] = ("Существующий:", "Existing:"),
        ["KeySetup.Done"] = ("Готово. Ключ: {0} ({1})", "Done. Key: {0} ({1})"),
        ["KeySetup.DoneButton"] = ("Готово", "Done"),
        ["KeySetup.NeedPassword"] = ("Для настройки нужен сохранённый пароль сервера", "A saved server password is required"),
        ["KeySetup.Connecting"] = ("Подключаюсь к {0} по паролю…", "Connecting to {0} with the password…"),
        ["KeySetup.PasswordOk"] = ("Вход по паролю выполнен.", "Password login succeeded."),
        ["KeySetup.KeyNotFound"] = ("Выбранный ключ не найден", "The selected key was not found"),
        ["KeySetup.UsingExisting"] = ("Использую существующий ключ «{0}» ({1}).", "Using the existing key \"{0}\" ({1})."),
        ["KeySetup.Generated"] = ("Сгенерирован новый ключ Ed25519 ({0}).", "Generated a new Ed25519 key ({0})."),
        ["KeySetup.BadChar"] = ("Недопустимый символ в публичном ключе", "Invalid character in the public key"),
        ["KeySetup.Adding"] = ("Добавляю ключ в ~/.ssh/authorized_keys…", "Adding the key to ~/.ssh/authorized_keys…"),
        ["KeySetup.WriteFailed"] = ("Не удалось записать authorized_keys:", "Could not write authorized_keys:"),
        ["KeySetup.Installed"] = ("Ключ установлен. Проверяю вход по ключу…", "Key installed. Checking key login…"),
        ["KeySetup.CheckFailed"] = ("Проверка входа по ключу не прошла", "Key login check failed"),
        ["KeySetup.KeyWorks"] = ("Вход по ключу работает.", "Key login works."),
        ["KeySetup.Switched"] = ("Сервер переключён на авторизацию по ключу. Пароль остаётся сохранённым — его можно удалить в настройках сервера.",
            "The server now uses key login. The password stays saved — you can remove it in the server settings."),

        // ---------- port forwards ----------
        ["Fwd.Title"] = ("Пробросы портов (iptables)", "Port forwards (iptables)"),
        ["Fwd.Hint"] = ("Трафик на порт этого сервера перенаправляется (DNAT + MASQUERADE) на другой сервер. Нужен root или sudo. Правила сохраняются после перезагрузки (netfilter-persistent / iptables-save).",
            "Traffic to a port of this server is redirected (DNAT + MASQUERADE) to another server. Requires root or sudo. Rules are kept across reboots (netfilter-persistent / iptables-save)."),
        ["Fwd.Protocol"] = ("Протокол", "Protocol"),
        ["Fwd.ListenPort"] = ("Порт", "Port"),
        ["Fwd.Target"] = ("Куда", "Target"),
        ["Fwd.Interface"] = ("Интерфейс", "Interface"),
        ["Fwd.CreatedBy"] = ("Создан", "Created by"),
        ["Fwd.External"] = ("внешний", "external"),
        ["Fwd.AddTitle"] = ("Новый проброс", "New forward"),
        ["Fwd.PortTip"] = ("Порт или диапазон 1000:2000", "Port or range 1000:2000"),
        ["Fwd.TargetServer"] = ("Целевой сервер или IP", "Target server or IP"),
        ["Fwd.TargetTip"] = ("Выберите сервер из списка или введите IP / хост", "Pick a server or type an IP / host"),
        ["Fwd.TargetPort"] = ("Порт цели", "Target port"),
        ["Fwd.TargetPortTip"] = ("Пусто — тот же порт", "Empty — same port"),
        ["Fwd.Add"] = ("Добавить", "Add"),
        ["Fwd.Refresh"] = ("Обновить", "Refresh"),
        ["Fwd.Delete"] = ("Удалить выбранный", "Delete selected"),
        ["Fwd.InstallPersist"] = ("Установить iptables-persistent", "Install iptables-persistent"),
        ["Fwd.InstallPersistConfirm"] = ("На сервере не найден способ сохранять правила iptables после перезагрузки.\nУстановить iptables-persistent (Debian/Ubuntu) или iptables-services (RHEL)?",
            "No way to keep iptables rules across reboots was found on the server.\nInstall iptables-persistent (Debian/Ubuntu) or iptables-services (RHEL)?"),
        ["Fwd.InstallingPersist"] = ("Устанавливаю пакет для сохранения правил…", "Installing the rule persistence package…"),
        ["Fwd.Reading"] = ("Читаю правила iptables на {0}…", "Reading iptables rules on {0}…"),
        ["Fwd.Found"] = ("Найдено пробросов: {0}", "Forwards found: {0}"),
        ["Fwd.FillFields"] = ("Укажите порт и цель.", "Enter a port and a target."),
        ["Fwd.Adding"] = ("Добавляю {0} {1} → {2}:{3}…", "Adding {0} {1} → {2}:{3}…"),
        ["Fwd.Added"] = ("Проброс добавлен.", "Forward added."),
        ["Fwd.DeleteConfirm"] = ("Удалить проброс {0} {1} → {2}?", "Delete forward {0} {1} → {2}?"),
        ["Fwd.Deleting"] = ("Удаляю проброс {0} {1}…", "Deleting forward {0} {1}…"),
        ["Fwd.Deleted"] = ("Проброс удалён.", "Forward deleted."),
        ["Fwd.Connecting"] = ("Подключаюсь к {0}…", "Connecting to {0}…"),
        ["Fwd.NeedRoot"] = ("Нужны права root: войдите как root или сохраните пароль пользователя с правом sudo.",
            "Root is required: log in as root or save the password of a sudo-capable user."),
        ["Fwd.Failed"] = ("Команда iptables не выполнилась:", "The iptables command failed:"),
        ["Fwd.Persisted"] = ("Правила сохранены ({0}).", "Rules saved ({0})."),
        ["Fwd.NotPersisted"] = ("Внимание: правила НЕ сохранятся после перезагрузки — нет netfilter-persistent / iptables-services.",
            "Warning: rules will NOT survive a reboot — no netfilter-persistent / iptables-services."),
        ["Fwd.BadProtocol"] = ("Протокол должен быть tcp или udp", "The protocol must be tcp or udp"),
        ["Fwd.BadPort"] = ("Неверный порт: {0}", "Invalid port: {0}"),
        ["Fwd.BadIp"] = ("Неверный IPv4-адрес: {0}", "Invalid IPv4 address: {0}"),
        ["Fwd.BadId"] = ("Неверный идентификатор правила: {0}", "Invalid rule id: {0}"),
        ["Fwd.NoRule"] = ("Не удалось определить правило для удаления", "Could not determine the rule to delete"),
        ["Fwd.CannotResolve"] = ("Не удалось определить IP для {0}", "Could not resolve {0}"),

        // ---------- scripts ----------
        ["Scripts.Title"] = ("Установочный скрипт", "Install script"),
        ["Scripts.NoneMenu"] = ("Нет скриптов — добавить в Настройках…", "No scripts — add some in Settings…"),
        ["Scripts.OtherOs"] = ("Для других ОС", "For other OSes"),
        ["Scripts.RunConfirm"] = ("Запустить скрипт «{0}» на сервере «{1}» ({2})?\n\nОн откроется в новой вкладке терминала.",
            "Run script \"{0}\" on server \"{1}\" ({2})?\n\nIt opens in a new terminal tab."),
        ["Scripts.Uploading"] = ("Загружаю «{0}» на {1}…", "Uploading \"{0}\" to {1}…"),
        ["Scripts.Started"] = ("Скрипт «{0}» запущен на {1}", "Script \"{0}\" started on {1}"),
        ["Scripts.Add"] = ("+ Скрипт", "+ Script"),
        ["Scripts.Duplicate"] = ("Копия", "Copy"),
        ["Scripts.Delete"] = ("Удалить", "Delete"),
        ["Scripts.Name"] = ("Название", "Name"),
        ["Scripts.OsFilter"] = ("Для ОС (ID из os-release)", "For OS (os-release ID)"),
        ["Scripts.OsFilterTip"] = ("ID из /etc/os-release, можно с версией: debian:12, ubuntu:24.04", "ID from /etc/os-release, optionally with a version: debian:12, ubuntu:24.04"),
        ["Scripts.AddOs"] = ("Добавить", "Add"),
        ["Scripts.OsHint"] = ("Ничего не выбрано — скрипт для любой ОС. Скрипты для ОС сервера показываются в меню первыми.",
            "Nothing selected = any OS. Scripts for the server's OS are listed first in the menu."),
        ["Scripts.RestoreBuiltins"] = ("Встроенные…", "Built-in…"),
        ["Scripts.RestoreBuiltinsTip"] = ("Вернуть удалённые встроенные скрипты и сбросить изменения в них", "Bring back deleted built-in scripts and undo edits to them"),
        ["Scripts.RestoreBuiltinsConfirm"] = ("Вернуть встроенные скрипты в исходный вид? Удалённые появятся снова, правки в них будут потеряны.",
            "Reset the built-in scripts? Deleted ones come back, edits to them are lost."),
        ["Scripts.BuiltinTag"] = ("встроенный", "built-in"),
        ["Scripts.AddCompose"] = ("+ Compose", "+ Compose"),
        ["Scripts.AddComposeTip"] = ("Новый скрипт типа Docker Compose: вместо bash — docker-compose.yml, программа сама разворачивает его на сервере",
            "New Docker Compose script: a docker-compose.yml instead of bash, the app deploys it on the server"),
        ["Scripts.NewCompose"] = ("Новый сервис (compose)", "New service (compose)"),
        ["Scripts.KindTip"] = ("Bash — обычный скрипт. Docker Compose — текст это docker-compose.yml: он кладётся в /opt/<@project>, параметры — в .env рядом, затем docker compose pull и up -d (Docker ставится сам, если его нет).",
            "Bash is a plain script. Docker Compose: the text is a docker-compose.yml that goes to /opt/<@project>, parameters go to .env next to it, then docker compose pull and up -d (Docker is installed first if missing)."),
        ["ScriptRun.ComposeInfo"] = ("Docker Compose: файл и .env с параметрами будут в /opt/{0}, затем docker compose pull && up -d. Если Docker нет, он установится.",
            "Docker Compose: the file and a .env with the parameters go to /opt/{0}, then docker compose pull && up -d. Docker is installed if missing."),
        ["Os.Any"] = ("{0} (любая версия)", "{0} (any version)"),
        ["Os.AnyDerived"] = ("{0} и производные ({1})", "{0} and derivatives ({1})"),
        ["Os.AllSystems"] = ("Любая ОС", "Any OS"),
        ["ScriptRun.Title"] = ("Запуск скрипта", "Run script"),
        ["ScriptRun.Header"] = ("{0} → {1} ({2})", "{0} → {1} ({2})"),
        ["ScriptRun.OsMismatch"] = ("Скрипт рассчитан на {0}, а на сервере {1}.", "The script is meant for {0} but the server runs {1}."),
        ["ScriptRun.OsUnknown"] = ("ОС ещё не определена", "an unknown OS"),
        ["ScriptRun.Ready"] = ("Заполните параметры и нажмите «Запустить». Вывод скрипта появится здесь, результаты сохранятся у сервера.",
            "Fill in the parameters and press \"Run\". The output shows up here; results are saved to the server."),
        ["ScriptRun.ReadyNoParams"] = ("Нажмите «Запустить». Вывод скрипта появится здесь.", "Press \"Run\". The output shows up here."),
        ["ScriptRun.Output"] = ("Вывод", "Output"),
        ["ScriptRun.Copy"] = ("Копировать", "Copy"),
        ["ScriptRun.Copied"] = ("Скопировано в буфер обмена", "Copied to the clipboard"),
        ["ScriptRun.InTerminal"] = ("В терминале", "In a terminal"),
        ["ScriptRun.InTerminalTip"] = ("Запустить в отдельной вкладке терминала — для скриптов, которые задают вопросы. Результаты не сохраняются.",
            "Run in a terminal tab, for scripts that ask questions. Results are not saved."),
        ["ScriptRun.InTerminalStarted"] = ("Запущен в терминале. Результаты будут показаны там, но не сохранятся.", "Started in a terminal. Results are shown there but not saved."),
        ["ScriptRun.Run"] = ("Запустить", "Run"),
        ["ScriptRun.RunAgain"] = ("Запустить снова", "Run again"),
        ["ScriptRun.Stop"] = ("Остановить", "Stop"),
        ["ScriptRun.Stopping"] = ("Останавливаю…", "Stopping…"),
        ["ScriptRun.Stopped"] = ("Остановлено", "Stopped"),
        ["ScriptRun.Connecting"] = ("Подключаюсь и загружаю скрипт…", "Connecting and uploading the script…"),
        ["ScriptRun.Running"] = ("Выполняется…", "Running…"),
        ["ScriptRun.Done"] = ("Готово за {0}", "Done in {0}"),
        ["ScriptRun.Failed"] = ("Скрипт завершился с кодом {0} (за {1})", "The script exited with code {0} (after {1})"),
        ["ScriptRun.SaveFailed"] = ("Не удалось сохранить результат:", "Could not save the result:"),
        ["ScriptRun.ResultsSaved"] = ("Результаты ({0}) сохранены у сервера — они в дереве, в разделе «Результаты скриптов»",
            "Results ({0}) are saved to the server, under \"Script results\" in the tree"),
        ["ScriptRun.CloseRunning"] = ("Скрипт ещё выполняется. Остановить его и закрыть окно?", "The script is still running. Stop it and close the window?"),
        ["ScriptRun.Required"] = ("Заполните «{0}»", "Fill in \"{0}\""),
        ["ScriptRun.NotNumber"] = ("«{0}» должно быть числом", "\"{0}\" must be a number"),
        ["ScriptRun.BadChoice"] = ("Недопустимое значение «{0}»", "Invalid value of \"{0}\""),
        ["Scripts.UseSudo"] = ("Запускать через sudo (если вход не под root)", "Run with sudo (when not logged in as root)"),
        ["Scripts.Save"] = ("Сохранить", "Save"),
        ["Scripts.NewName"] = ("Новый скрипт", "New script"),
        ["Scripts.DeleteConfirm"] = ("Удалить скрипт «{0}»?", "Delete script \"{0}\"?"),

        // ---------- backup ----------
        ["Backup.Title"] = ("Резервная копия", "Backup"),
        ["Backup.ToFolder"] = ("В папку на диске", "To a folder"),
        ["Backup.ToServer"] = ("На сервер по SSH (SFTP)", "To a server over SSH (SFTP)"),
        ["Backup.Browse"] = ("Обзор…", "Browse…"),
        ["Backup.ChooseFolder"] = ("Папка для резервных копий", "Backup folder"),
        ["Backup.Server"] = ("Сервер", "Server"),
        ["Backup.RemotePath"] = ("Папка на сервере (относительно домашней)", "Remote folder (relative to home)"),
        ["Backup.Keep"] = ("Хранить копий:", "Keep copies:"),
        ["Backup.AutoHours"] = ("Автоматически каждые N часов (0 — выкл.):", "Automatically every N hours (0 = off):"),
        ["Backup.Hint"] = ("Архив содержит всю папку data; vault.dat внутри зашифрован мастер-паролем, который был на момент бэкапа. Чтобы вернуть данные, нажмите «Восстановить из копии…»: можно взять последнюю копию из папки или с сервера, либо выбрать любой файл sshmanager-data-*.zip. Текущие данные перед заменой сохраняются в data\\backups\\before-restore-*.zip. Если программа не запускается — закройте её и распакуйте архив в папку data вручную.",
            "The archive holds the whole data folder; vault.dat inside is encrypted with the master password you had at backup time. To get data back, press \"Restore from backup…\": take the newest copy from the folder or server, or pick any sshmanager-data-*.zip file. The current data is saved to data\\backups\\before-restore-*.zip first. If the app does not start, close it and unpack the archive into the data folder by hand."),
        ["Restore.Button"] = ("Восстановить из копии…", "Restore from backup…"),
        ["Restore.Title"] = ("Восстановление из резервной копии", "Restore from backup"),
        ["Restore.ChooseSource"] = ("Взять последнюю копию из «{0}»?\n\nДа — последняя копия оттуда.\nНет — выбрать файл .zip на диске.",
            "Take the newest copy from \"{0}\"?\n\nYes — the newest copy from there.\nNo — pick a .zip file on disk."),
        ["Restore.Filter"] = ("Резервные копии SSH Manager (*.zip)|*.zip", "SSH Manager backups (*.zip)|*.zip"),
        ["Restore.Downloading"] = ("Загружаю резервную копию…", "Downloading the backup…"),
        ["Restore.NoneFound"] = ("Резервных копий там нет.", "No backups found there."),
        ["Restore.NotBackup"] = ("Это не резервная копия SSH Manager (в архиве нет vault.dat).", "This is not an SSH Manager backup (no vault.dat inside)."),
        ["Restore.PasswordPrompt"] = ("Мастер-пароль, который был на момент этой копии:\n{0}", "Master password as it was when this copy was made:\n{0}"),
        ["Restore.Checking"] = ("Проверяю пароль…", "Checking the password…"),
        ["Restore.WrongPassword"] = ("Пароль не подходит к этой копии, попробуйте ещё раз.", "The password does not open this copy, try again."),
        ["Restore.Confirm"] = ("Заменить текущие серверы, ключи и настройки данными из копии?\n{0}\n\nТекущие данные сначала сохранятся в data\\backups, окно откроется заново.",
            "Replace the current servers, keys and settings with this copy?\n{0}\n\nThe current data is saved to data\\backups first; the window will reopen."),
        ["Restore.Done"] = ("Данные восстановлены из\n{0}\n\nПрежние данные сохранены в\n{1}\nЧтобы откатиться, восстановите этот файл тем же способом.",
            "Data restored from\n{0}\n\nThe previous data is saved in\n{1}\nTo undo, restore that file the same way."),
        ["Backup.Never"] = ("Бэкап ещё не делался", "No backup yet"),
        ["Backup.Running"] = ("Создаю резервную копию…", "Creating a backup…"),
        ["Backup.Done"] = ("Резервная копия сохранена: {0}", "Backup saved: {0}"),
        ["Backup.ResultOk"] = ("Последний бэкап {0:g}: {1}", "Last backup {0:g}: {1}"),
        ["Backup.ResultFailed"] = ("Ошибка бэкапа {0:g}: {1}", "Backup failed {0:g}: {1}"),
        ["Backup.NotConfigured"] = ("Укажите, куда сохранять резервные копии (Настройки → Резервное копирование).",
            "Choose where to store backups (Settings → Backup)."),
        ["Backup.ServerMissing"] = ("Сервер для бэкапа не найден в хранилище", "The backup server is not in the vault"),
        ["Backup.AutoFailed"] = ("Автоматический бэкап не удался:", "Automatic backup failed:"),

        // ---------- settings ----------
        ["Settings.Interface"] = ("Интерфейс", "Interface"),
        ["Settings.Language"] = ("Язык / Language:", "Language / Язык:"),
        ["Settings.Startup"] = ("Запуск и трей", "Startup and tray"),
        ["Settings.AutostartBox"] = ("Запускать вместе с Windows (сразу в трей, заблокированным)", "Start with Windows (in the tray, locked)"),
        ["Settings.CloseToTray"] = ("Кнопка закрытия сворачивает в трей (агент продолжает работать)", "The close button hides to the tray (the agent keeps running)"),
        ["Settings.Autostart.Title"] = ("Автозапуск", "Autostart"),
        ["Settings.Autostart.Failed"] = ("Не удалось изменить автозапуск:", "Could not change autostart:"),
        ["Settings.Security"] = ("Безопасность", "Security"),
        ["Settings.AutoLock"] = ("Автоблокировка после простоя ПК, минут (0 — никогда):", "Lock after PC idle time, minutes (0 = never):"),
        ["Settings.LockOnWinL"] = ("Блокировать при блокировке Windows (Win+L)", "Lock when Windows locks (Win+L)"),
        ["Settings.UnlockOnAgent"] = ("Показывать окно разблокировки, когда ssh / git / VS Code обращаются к агенту",
            "Show the unlock window when ssh / git / VS Code ask the agent"),
        ["Settings.ChangePassword"] = ("Сменить мастер-пароль…", "Change master password…"),
        ["Settings.Monitoring"] = ("Мониторинг и сведения о серверах", "Monitoring and server information"),
        ["Settings.MonitorInterval"] = ("Проверять доступность каждые, минут (0 — выкл.):", "Check availability every, minutes (0 = off):"),
        ["Settings.MonitorHint"] = ("Проверяется TCP-подключение к SSH-порту (с ответом sshd) и к отслеживаемым портам. Если SSH не отвечает, но отслеживаемый порт открыт, сервер считается доступным. Каждая проверка пишется в историю (data\\uptime) — из неё считается аптайм. Для отдельного сервера интервал меняется в его настройках.",
            "A TCP connection to the SSH port (with the sshd greeting) and to the monitored ports is checked. If SSH does not answer but a monitored port is open, the server counts as up. Every check goes to the history (data\\uptime) the uptime is computed from. Per-server intervals are set in the server editor."),
        ["Settings.CollectMetrics"] = ("После проверки заходить по SSH и снимать загрузку CPU, памяти и диска", "After a check, log in over SSH to read CPU, memory and disk usage"),
        ["Settings.NotifyDown"] = ("Уведомлять в трее, когда сервер становится недоступен", "Notify in the tray when a server goes down"),
        ["Settings.AutoInventory"] = ("Определять ОС, Docker-контейнеры, сервисы и пробросы автоматически", "Detect OS, Docker containers, services and forwards automatically"),
        ["Settings.GeoIp"] = ("Определять страну и город сервера (GeoIP)", "Detect server country and city (GeoIP)"),
        ["Settings.GeoIpHint"] = ("IP-адреса серверов отправляются в онлайн-сервис ipwho.is (запасной — ip-api.com); результат кэшируется на 30 дней.",
            "Server IP addresses are sent to the online service ipwho.is (fallback ip-api.com); results are cached for 30 days."),
        ["Settings.Scripts"] = ("Установочные скрипты", "Install scripts"),
        ["Settings.ScriptsHint"] = ("Скрипт (bash) появляется в меню сервера «Установить» и запускается в окне программы: вывод виден сразу, а результаты сохраняются у сервера. Параметры и результаты описываются в комментариях: «# @param ИМЯ text|number|choice|bool|secret label=\"…\" default=… options=a,b required when=ДРУГОЙ=значение» и «# @result ИМЯ label=\"…\" [monitor=Имя]». Параметры приходят как переменные окружения, результат скрипт пишет строками ИМЯ=значение в файл $SSHM_RESULT. Также доступны SSHM_SERVER_NAME и SSHM_HOST. Скрипты хранятся в зашифрованном хранилище.",
            "A (bash) script appears in the server menu \"Install\" and runs in an app window: the output is live and results are saved to the server. Parameters and results are described in comments: \"# @param NAME text|number|choice|bool|secret label=\"…\" default=… options=a,b required when=OTHER=value\" and \"# @result NAME label=\"…\" [monitor=Name]\". Parameters arrive as environment variables; the script writes results as NAME=value lines to the file $SSHM_RESULT. SSHM_SERVER_NAME and SSHM_HOST are set too. Scripts are stored in the encrypted vault."),
        ["Settings.Backup"] = ("Резервное копирование", "Backup"),
        ["Settings.Terminal"] = ("Терминал", "Terminal"),
        ["Settings.WtTab"] = ("Windows Terminal — новая вкладка", "Windows Terminal — new tab"),
        ["Settings.WtWindow"] = ("Windows Terminal — новое окно", "Windows Terminal — new window"),
        ["Settings.Console"] = ("Обычное окно консоли", "Plain console window"),
        ["Settings.BuiltIn"] = ("Встроенный терминал — вкладка в окне программы", "Built-in terminal — a tab in the app window"),
        ["Term.Connecting"] = ("Подключаюсь к {0}\n{1}…", "Connecting to {0}\n{1}…"),
        ["Term.ConnectFailed"] = ("Не удалось подключиться: {0}\nEnter — попробовать снова, Ctrl+Shift+W — закрыть вкладку.",
            "Could not connect: {0}\nEnter to try again, Ctrl+Shift+W to close the tab."),
        ["Term.Ended"] = ("[сессия завершена — Enter: подключиться снова, Ctrl+Shift+W: закрыть]", "[session ended — Enter: reconnect, Ctrl+Shift+W: close]"),
        ["Term.Lost"] = ("[соединение потеряно: {0} — Enter: переподключиться]", "[connection lost: {0} — Enter: reconnect]"),
        ["Term.ConnectionLost"] = ("сервер закрыл соединение", "the server closed the connection"),
        ["Term.WebViewMissing"] = ("Встроенному терминалу нужен Microsoft Edge WebView2 Runtime (есть в Windows 11). Установите его или выберите другой терминал в настройках.\n\n{0}",
            "The built-in terminal needs the Microsoft Edge WebView2 Runtime (part of Windows 11). Install it or pick another terminal in the settings.\n\n{0}"),
        ["Term.CloseTab"] = ("Закрыть (Ctrl+Shift+W, средняя кнопка мыши)", "Close (Ctrl+Shift+W, middle click)"),
        ["Term.CloseAllConfirm"] = ("Открыто терминалов: {0}. Закрыть их и выйти?", "{0} terminal(s) are open. Close them and exit?"),
        ["Term.TabTip"] = ("{0}\n{1}\nCtrl+Tab — следующая вкладка, Ctrl+Shift+T — ещё одна сессия, Ctrl+Shift+W — закрыть",
            "{0}\n{1}\nCtrl+Tab: next tab, Ctrl+Shift+T: another session, Ctrl+Shift+W: close"),
        ["Term.MenuCopy"] = ("Копировать", "Copy"),
        ["Term.MenuPaste"] = ("Вставить", "Paste"),
        ["Term.MenuSelectAll"] = ("Выделить всё", "Select all"),
        ["Term.MenuClear"] = ("Очистить экран", "Clear screen"),
        ["Term.SuggestHint"] = ("Tab — вставить · ↑↓ — выбрать · Esc — скрыть · → — принять серую подсказку",
            "Tab: insert · ↑↓: choose · Esc: hide · →: accept the grey suggestion"),
        ["Settings.TermIntegration"] = ("Интеграция с bash / zsh во встроенном терминале: подсказки, текущая папка, команда edit",
            "bash / zsh integration in the built-in terminal: suggestions, current folder, the edit command"),
        ["Settings.TermAutoSuggest"] = ("Показывать подсказки при наборе (иначе по Ctrl+Space)", "Show suggestions while typing (otherwise Ctrl+Space)"),
        ["Settings.TermSuggestHint"] = ("Подсказки берутся из истории команд сервера, списка команд, файлов, контейнеров и сервисов. Ничего не меняется в файлах на сервере — интеграция загружается из ~/.cache/sshm на время сессии.",
            "Suggestions come from the server's command history, commands, files, containers and services. No rc files are changed — the integration is loaded from ~/.cache/sshm for the session."),
        ["Main.Files"] = ("Файлы", "Files"),
        ["Main.FilesTip"] = ("Файловый менеджер (SFTP): компьютер слева, сервер справа", "File manager (SFTP): this PC on the left, the server on the right"),
        ["Ctx.Files"] = ("Файлы (SFTP)…", "Files (SFTP)…"),
        ["Tab.NewTerminal"] = ("Новый терминал здесь", "New terminal here"),
        ["Tab.Files"] = ("Файлы здесь", "Files here"),
        ["Tab.Close"] = ("Закрыть", "Close"),
        ["Tab.CloseOthers"] = ("Закрыть остальные вкладки", "Close other tabs"),

        ["Files.Title"] = ("Файлы", "Files"),
        ["Files.Marked"] = ("выделено: {0} ({1})", "{0} marked ({1})"),
        ["Files.MarkMask"] = ("Выделить по маске…", "Mark by mask…"),
        ["Files.UnmarkMask"] = ("Снять выделение по маске…", "Unmark by mask…"),
        ["Files.InvertMarks"] = ("Инвертировать выделение", "Invert marks"),
        ["Files.MaskPrompt"] = ("Маска файлов, можно несколько через ; (например *.yml;*.conf):", "File mask, several separated by ; (e.g. *.yml;*.conf):"),
        ["Files.TabTip"] = ("Файлы {0}\n{1}\nF5 — копировать, F6 — переместить, F7 — папка, F8 — удалить, F4 — редактировать",
            "Files of {0}\n{1}\nF5: copy, F6: move, F7: folder, F8: delete, F4: edit"),
        ["Files.NoJump"] = ("Файловый менеджер пока не работает через jump-хост и дополнительные параметры ssh.",
            "The file manager does not work through a jump host or extra ssh arguments yet."),
        ["Files.ThisPc"] = ("Этот компьютер", "This PC"),
        ["Files.Free"] = ("свободно {0}", "{0} free"),
        ["Files.Status"] = ("папок: {0}, файлов: {1} ({2})", "{0} folders, {1} files ({2})"),
        ["Files.HiddenCount"] = ("скрытых: {0}", "{0} hidden"),
        ["Files.Refresh"] = ("Обновить", "Refresh"),
        ["Files.Home"] = ("Домашняя папка", "Home folder"),
        ["Files.Up"] = ("Вверх (Backspace)", "Up (Backspace)"),
        ["Files.Size"] = ("Размер", "Size"),
        ["Files.Modified"] = ("Изменён", "Modified"),
        ["Files.Permissions"] = ("Права", "Mode"),
        ["Files.Owner"] = ("Владелец", "Owner"),
        ["Files.Open"] = ("Открыть", "Open"),
        ["Files.Edit"] = ("Редактировать", "Edit"),
        ["Files.Rename"] = ("Переименовать", "Rename"),
        ["Files.NewName"] = ("Новое имя:", "New name:"),
        ["Files.Chmod"] = ("Права доступа…", "Permissions…"),
        ["Files.ChmodPrompt"] = ("Права для {0} (восьмерично, например 644 или 755):", "Mode for {0} (octal, e.g. 644 or 755):"),
        ["Files.BadMode"] = ("Нужно восьмеричное число из 3–4 цифр, например 644.", "Enter a 3–4 digit octal number, e.g. 644."),
        ["Files.CopyPath"] = ("Копировать путь", "Copy path"),
        ["Files.Delete"] = ("Удалить", "Delete"),
        ["Files.DeleteConfirm"] = ("Удалить {0}? Папки удаляются со всем содержимым.", "Delete {0}? Folders are deleted with everything in them."),
        ["Files.ItemsCount"] = ("{0} объект(ов)", "{0} item(s)"),
        ["Files.NewFolder"] = ("Новая папка", "New folder"),
        ["Files.FolderName"] = ("Имя папки:", "Folder name:"),
        ["Files.NewFile"] = ("Новый файл", "New file"),
        ["Files.FileName"] = ("Имя файла:", "File name:"),
        ["Files.Exists"] = ("{0} уже существует.", "{0} already exists."),
        ["Files.BadName"] = ("Недопустимое имя.", "This name is not allowed."),
        ["Files.TerminalHere"] = ("Терминал здесь", "Terminal here"),
        ["Files.Explorer"] = ("Показать в проводнике", "Show in Explorer"),
        ["Files.ShowHidden"] = ("Скрытые файлы", "Hidden files"),
        ["Files.Retry"] = ("Повторить", "Retry"),
        ["Files.Upload"] = ("Загрузить на сервер", "Upload"),
        ["Files.Download"] = ("Скачать", "Download"),
        ["Files.MoveUpload"] = ("Переместить на сервер", "Move to the server"),
        ["Files.MoveDownload"] = ("Переместить на компьютер", "Move to this PC"),
        ["Files.CopyButton"] = ("Копировать", "Copy"),
        ["Files.MoveButton"] = ("Переместить", "Move"),
        ["Files.KeysHint"] = ("Insert, Shift+ПКМ — отметить · Num + / − / * — по маске · Tab — другая панель · перетаскивание из проводника",
            "Insert, Shift+right click: mark · Num + / − / *: by mask · Tab: other panel · drag from Explorer"),
        ["Files.Transfers"] = ("Передачи", "Transfers"),
        ["Files.ClearDone"] = ("Убрать завершённые", "Clear finished"),
        ["Files.Uploading"] = ("Загрузка", "Upload"),
        ["Files.Downloading"] = ("Скачивание", "Download"),
        ["Files.Moving"] = ("Перемещение", "Move"),
        ["Files.TransferDone"] = ("готово: {0} файлов, {1}", "done: {0} files, {1}"),
        ["Files.Skipped"] = ("пропущено: {0}", "{0} skipped"),
        ["Files.TransferCanceled"] = ("отменено", "canceled"),
        ["Files.TransferFailed"] = ("ошибка: {0}", "failed: {0}"),
        ["Files.CloseWithTransfers"] = ("Идёт передача файлов. Прервать её и закрыть вкладку?", "Files are being transferred. Stop and close the tab?"),
        ["Files.ConflictTitle"] = ("Файл существует", "File exists"),
        ["Files.ConflictHeader"] = ("«{0}» уже есть в папке назначения", "\"{0}\" already exists in the destination"),
        ["Files.ConflictNew"] = ("Копируемый:", "Copying:"),
        ["Files.ConflictExisting"] = ("Существующий:", "Existing:"),
        ["Files.Folder"] = ("папка", "folder"),
        ["Files.Overwrite"] = ("Заменить", "Replace"),
        ["Files.OverwriteAll"] = ("Заменить все", "Replace all"),
        ["Files.Skip"] = ("Пропустить", "Skip"),
        ["Files.SkipAll"] = ("Пропустить все", "Skip all"),

        ["TextEd.Title"] = ("Редактор", "Editor"),
        ["TextEd.TabTip"] = ("{0}\n{1}\nCtrl+S — сохранить, Ctrl+F — поиск, Ctrl+H — замена, Alt+Z — перенос строк",
            "{0}\n{1}\nCtrl+S: save, Ctrl+F: find, Ctrl+H: replace, Alt+Z: word wrap"),
        ["TextEd.Save"] = ("Сохранить", "Save"),
        ["TextEd.Reload"] = ("Перечитать", "Reload"),
        ["TextEd.Wrap"] = ("Перенос строк", "Word wrap"),
        ["TextEd.Loading"] = ("Открываю {0}…", "Opening {0}…"),
        ["TextEd.LoadFailed"] = ("Не удалось открыть файл:\n{0}", "Could not open the file:\n{0}"),
        ["TextEd.NewFile"] = ("новый файл — будет создан при сохранении", "new file — created on save"),
        ["TextEd.Status"] = ("Стр {0}, стлб {1}", "Ln {0}, Col {1}"),
        ["TextEd.Selected"] = ("выделено {0}", "{0} selected"),
        ["TextEd.Saved"] = ("Сохранено", "Saved"),
        ["TextEd.SaveFailed"] = ("Не удалось сохранить: {0}", "Could not save: {0}"),
        ["TextEd.CloseConfirm"] = ("Сохранить изменения в {0}?", "Save changes to {0}?"),
        ["TextEd.ReloadConfirm"] = ("Отбросить изменения в {0} и перечитать файл с сервера?", "Discard the changes to {0} and reload it from the server?"),
        ["TextEd.ChangedOnServer"] = ("{0} изменился на сервере после открытия. Перезаписать?", "{0} was changed on the server since it was opened. Overwrite it?"),
        ["TextEd.SaveWithSudo"] = ("Нет прав на запись {0}. Сохранить через sudo?", "No permission to write {0}. Save with sudo?"),
        ["TextEd.SudoFailed"] = ("sudo отказал: {0}", "sudo refused: {0}"),
        ["TextEd.Denied"] = ("Нет доступа к файлу.", "Access to the file is denied."),
        ["TextEd.Binary"] = ("Это двоичный файл — скачайте его через файловый менеджер.", "This is a binary file — download it with the file manager."),
        ["TextEd.IsFolder"] = ("Это папка.", "This is a folder."),
        ["TextEd.TooLarge"] = ("Файл больше {0} МБ — скачайте его через файловый менеджер.", "The file is larger than {0} MB — download it with the file manager."),
        ["Hotkey.Label"] = ("Горячая клавиша окна (во всей системе):", "Global shortcut for the window:"),
        ["Hotkey.Tip"] = ("Щёлкните и нажмите сочетание (с Ctrl, Alt, Shift или Win). Backspace — выключить.",
            "Click and press a combination (with Ctrl, Alt, Shift or Win). Backspace turns it off."),
        ["Hotkey.Default"] = ("По умолчанию", "Default"),
        ["Hotkey.Clear"] = ("Выключить", "Turn off"),
        ["Hotkey.Off"] = ("выключена", "off"),
        ["Hotkey.Works"] = ("работает: показывает окно, повторно — прячет", "works: shows the window, again hides it"),
        ["Hotkey.Taken"] = ("не работает — сочетание занято другой программой, выберите другое", "not working — another program uses it, pick another"),
        ["Update.Title"] = ("Обновления", "Updates"),
        ["Update.Version"] = ("Версия {0}", "Version {0}"),
        ["Update.CheckNow"] = ("Проверить обновления", "Check for updates"),
        ["Update.Install"] = ("Обновить и перезапустить", "Update and restart"),
        ["Update.WhatsNew"] = ("Что нового", "What's new"),
        ["Update.Auto"] = ("Проверять обновления автоматически (раз в день)", "Check for updates automatically (once a day)"),
        ["Update.Hint"] = ("Новые версии берутся из релизов github.com/nickolsky/ssh-manager (архив сверяется по SHA-256). Обновляются только файлы программы — папка data не трогается.",
            "New versions come from the github.com/nickolsky/ssh-manager releases (the archive is checked against its SHA-256). Only program files are replaced — the data folder is not touched."),
        ["Update.Checking"] = ("проверяю…", "checking…"),
        ["Update.UpToDate"] = ("установлена последняя версия ({0})", "you have the latest version ({0})"),
        ["Update.Available"] = ("доступна версия {0}", "version {0} is available"),
        ["Update.AvailableBalloon"] = ("Доступна версия {0}. Установить: Настройки → Обновления.", "Version {0} is available. Install it in Settings → Updates."),
        ["Update.CheckFailed"] = ("не удалось проверить: {0}", "could not check: {0}"),
        ["Update.NoReleases"] = ("релизов пока нет", "no releases yet"),
        ["Update.Downloading"] = ("скачиваю {0}…", "downloading {0}…"),
        ["Update.Installing"] = ("устанавливаю…", "installing…"),
        ["Update.InstallFailed"] = ("не удалось обновить: {0}", "update failed: {0}"),
        ["Update.BadChecksum"] = ("контрольная сумма архива не совпадает", "the archive checksum does not match"),
        ["Update.BadPackage"] = ("в архиве нет SshManager.exe", "SshManager.exe is not in the archive"),
        ["Update.Confirm"] = ("Установить версию {0}? Программа перезапустится, открытые терминалы и вкладки закроются.",
            "Install version {0}? The app restarts; open terminals and tabs are closed."),
        ["Settings.WtFound"] = ("Windows Terminal найден:", "Windows Terminal found:"),
        ["Settings.WtMissing"] = ("Windows Terminal не найден — сессии будут открываться в обычном окне консоли",
            "Windows Terminal not found — sessions open in a plain console window"),
        ["Settings.WtProfile"] = ("Профиль Windows Terminal (необязательно)", "Windows Terminal profile (optional)"),
        ["Settings.SshPath"] = ("Путь к ssh.exe (пусто — системный OpenSSH)", "Path to ssh.exe (empty = system OpenSSH)"),
        ["Settings.SshUsed"] = ("Используется:", "In use:"),
        ["Settings.AliveInterval"] = ("ServerAliveInterval, секунд (0 — выкл.):", "ServerAliveInterval, seconds (0 = off):"),
        ["Settings.HelperInfo"] = ("Из любого терминала: \"{0}\" <имя сервера>  (добавьте папку в PATH, чтобы писать просто sshm <имя>)",
            "From any terminal: \"{0}\" <server name>  (add the folder to PATH to type just sshm <name>)"),
        ["Settings.Data"] = ("Данные", "Data"),
        ["Settings.DataHint"] = ("vault.dat — зашифрованное хранилище, backups — его предыдущие версии, known_hosts — ключи серверов, pub — публичные ключи. Для резервной копии используйте раздел выше или скопируйте всю папку data и помните мастер-пароль.",
            "vault.dat is the encrypted vault, backups holds its previous versions, known_hosts the server keys, pub the public keys. Use the backup section above or copy the whole data folder — and remember the master password."),
    };
}
