<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sshm</AssemblyName>
    <RootNamespace>SshManager.Cli</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SshManager.Core\SshManager.Core.csproj" />
  </ItemGroup>

</Project>
